### ISSUE TITLE
Search isn't working correctly because of lack of formatter

### ISSUE THREAD

**Issue by eviltoylet** [bebraw/reactabular#10]
The current search implementation expects that `columns` contains a `formatter` field. There currently isn't a way to get to it because the current formatter lives in the `cell` object.

Is there any reason that `formatter` and `editor` don't just live on `columns`? `Cell` can be abstracted away for the user and created within `Table.render()`. This will allow removal of conditional code based on the presence of cell.

I'm more than happy to make these changes.

**Comment by bebraw** [comment]
Yeah, this sounds like a good change to make. I probably went too far with abstraction. In the process I forgot to update `search` implementation to take formatting in count. I wouldn't have any problem merging your PR. Thanks. :)

**Comment by bebraw** [comment]
I recall the main reason for making cell customizable had to do with the fact that sometimes you might want to render something that's not included within the data (ie. custom controls for edit, delete). I guess in the scheme you are proposing this would go to `formatter` field so there shouldn't be a problem I think.

**Comment by eviltoylet** [comment]
Great! I'll take a deeper look tonight. I haven't spent much time looking at the role of `editor` though. What's the motivation behind that? Any future plans for it? (e.g. hook into a persistent store)

**Comment by bebraw** [comment]
> Great! I'll take a deeper look tonight. I haven't spent much time looking at the role of editor though. What's the motivation behind that? Any future plans for it? (e.g. hook into a persistent store)

Cells implement standard interface (`(property, value, rowIndex, columnIndex)`). `lib/cell` and editors build on top of that. Each editor expects properties `value` and `onValue`. That is handled by `lib/cell` abstraction.

Internally `lib/cell` tracks edited cells in its parents state and modifies data. Now that I think of it, this isn't ideal. I suppose it should expose that the bit where it does `context.setState` over data as a callback. Then you could hook a persistent store into it. This would be consistent with rest of the design.

I hope that clears things up. :)

**Comment by eviltoylet** [comment]
Apologies for the spaminess here. I force pushed changes a few times as I discovered issues with my changes. Turns out GitHub still keeps those commits around.

**Comment by bebraw** [comment]
No problem. I'll go through the PR in a bit.
