### ISSUE TITLE
Error type.toUpper

### ISSUE THREAD

**Issue by eduardodelaguila** [bebraw/reactabular#101]
Hi!, today i installed Reactable, it is everything i need for my data display, but when i tried to implement your table i got Uncaught TypeError: type.toUpperCase is not a function, at first thought i believe that was my data or column definition, so i got your example and rigged up on my view, but i got the same error. 

Am i doing something wrong ?

My data, columns, require and call 
http://pastebin.com/euwFWL03

**Comment by bebraw** [comment]
You need to wrap

```javascript
<div id="sdefTable">
              <Reactabular columns={columns} data={data} rowKey={'id'} />
            </div>
```

within a React component definition. Otherwise it blows up at React side like that. See `demos/` for more practical examples and how to wrap it.

**Comment by eduardodelaguila** [comment]
You mean something like this?

var DetailsContainer= React.createClass({

    render: function() {
      return (
)
});

**Comment by bebraw** [comment]
@eduardodelaguila Can you upload a complete example at GitHub? I tried using your column/data definition but it worked for me...

**Comment by eduardodelaguila** [comment]
Right now i cant, i'll do it at night.

P.S. I'm a newbe on React.JS and English is not my native language, so sorry for any mistake :p

**Comment by bebraw** [comment]
@eduardodelaguila No worries. I'll have a look at your code tomorrow.

**Comment by eduardodelaguila** [comment]
thanks! :D

**Comment by bebraw** [comment]
@eduardodelaguila Any update? Can you upload some code for me to look at?
