### ISSUE TITLE
How to display clickable links in the table?

### ISSUE THREAD

**Issue by 90abyss** [bebraw/reactabular#102]
In one of my columns I have URL links. I just need to do a 

< a h ref = "URL coming from json"> Link </ a>

How should I incorporate this in my URL column in the table?

**Comment by bebraw** [comment]
See [the cell interface](https://github.com/bebraw/reactabular#implementing-custom-cell-operations). You can have a function like this there:

```javascript
cell: (url) => <a href={url}>{url}</a>
```

The exact code you need depends on your JSON structure of course.

**Comment by 90abyss** [comment]
Perfect its working! Can I have an if clause inside that cell property? I mean I want to display a clickable link only if the "TLink" has an "http://" in it. Otherwise I just want to display the text "DM". (From the json data I'm either getting a proper URL Link or the text "DM")

Something like this:

                    property: 'TLink',
                    header: 'Tweet Link',
                    cell: IF (TLink ! = "DM") => <a href={TLink}>Link</a>

How to make it work? Thanks again.

**Comment by bebraw** [comment]
Yeah. You can use a ternary for example:

```javascript
cell: (url) => {url === 'DM' ? <span>DM</span> : <a href={url}>{url}</a>}
```

If you have time, please read [my book](http://survivejs.com/). You should be able to pick up these kind things there easily.

**Comment by 90abyss** [comment]
I couldn't get it to work, can you please check if this is correct? The Link column is displayed completely empty.


                    property: 'Link',
                    header: 'Tweet Link',
                    cell: (Link) => {Link === 'DM' ? <span>DM</span> : <a href={Link}>Link</a>}

From the json data for the Link column, I'm either getting "DM" or the full URL "http://www.twitter.com/2738273/blah"

I'll surely read your book, you have no idea how much of a learning experience this has been for me.

**Comment by bebraw** [comment]
Here's a better example (added to repo as well):

```javascript
cell: (lovesBeeGees) =>
    lovesBeeGees ?
    <span>Loves BeeGees</span> :
    <span>Does not love BeeGees</span>
```

I think the problem is that `() => {}` form returns `undefined` by default. Either we need to do it like above or spell it out and have a `return` statement:

```
cell: (lovesBeeGees) => {
   return lovesBeeGees ?
      <span>Loves BeeGees</span> :
      <span>Does not love BeeGees</span>;
}
```

**Comment by 90abyss** [comment]
Perfection! Thank you for always having answers to all my questions!

**Comment by 90abyss** [comment]
What if I have multiple links for one column ie lets say the json data coming for my "Link" column above gives this : "http://github.com http://www.reddit.com/top/"
So in this case if I do as mentioned above: I'm getting a clickable URL link for the entire string - in the browser its opening as "http://github.com%20http://www.reddit.com/top/"
How do I get it to delimit the string returned from json data on space character and create two separate clickable links instead "http://github.com" and "http://www.reddit.com/top/"?

Thanks. And sorry for asking so many questions.

**Comment by bebraw** [comment]
@90abyss Something like this:

```javascript
(value) => {
  return value.split(' ').map((part) =>
    <a href={part}>{part}</a>
  );
}
```

**Comment by OKNoah** [comment]
@bebraw That link above is now dead.

**Comment by OKNoah** [comment]
Here's how I got this to work

    const columns = [{
      property: 'url',
      header: {
        label: 'Link'
      },
      cell: {
        formatters: [
          (label) => (
            <a href={label}>{label}</a>
          )
        ]
      }
    }]

**Comment by bebraw** [comment]
Ah, yeah. For reference [see the official site](https://reactabular.js.org/#/column-definition). It's all there. 👍
