### ISSUE TITLE
Cannot export reactabular as globals

### ISSUE THREAD

**Issue by AkshatM** [bebraw/reactabular#103]
I'm attempting to create a very simple isomorphic scheme with Reactabular and Handlebars. 

To do this, I'm Browserifying a file `source.js` that reads just 

```
module.exports = require('reactabular').Table;
```

in such a way that this React component becomes [globally accessible](http://makerlog.org/posts/creating-js-library-builds-with-browserify-and-other-npm-modules/) to the browser (so I can embed it in other scripts, for example):
```
browserify source.js --standalone Table > build.js
```

However, including this Browserified file results in the error message
```
Uncaught TypeError: columns.map is not a function
```
on the Chrome console. 

Is there any way to be able to accomplish this task, or get around it?

**Comment by bebraw** [comment]
Please note that the default build at `dist/` uses UMD. You get global/AMD/CommonJS access to it through that. Perhaps that's enough?

**Comment by bebraw** [comment]
Did you manage to resolve this?

**Comment by AkshatM** [comment]
No, we eventually went ahead with another solution instead. Sorry!
