### ISSUE TITLE
only th gets class from 'classes'

### ISSUE THREAD

**Issue by mmoutenot** [bebraw/reactabular#104]
> classes allows you to attach custom CSS classes per column. It uses classnames internally.

It looks like it adds it to the th, but not td's of the same column. Is this expected behavior?

**Comment by bebraw** [comment]
Yeah, it's expected. The `cell` interface is very flexible and allows styling.

I feel we should probably drop header `classes` and provide a more generic way to inject props instead. Perhaps something like that `cell` interface of ours.

**Comment by bebraw** [comment]
A quick heads-up. I dropped the support for `classes` at `0.9.0`. If you need to tweak classes, just go through `className`. This works for headers and cell definitions. There's also a row specific hook where you can inject.

**Comment by mmoutenot** [comment]
Awesome! I'll try it out soon.

**Comment by goldensunliu** [comment]
@bebraw it is actually `headerClass` no `className`
for now I am proposing a change to the doc https://github.com/bebraw/reactabular/pull/113 until all `column.headerClass` is all refactored out of the current code

**Comment by bebraw** [comment]
@goldensunliu Thanks! I could use your feedback on #109. I think that would clean up the API somewhat.
