### ISSUE TITLE
Ability to use Custom Sort Function?

### ISSUE THREAD

**Issue by damassi** [bebraw/reactabular#105]
Is it possible to create custom sorters? Right now I have a column of dates and numbers, but it seems that sorting is only string based out of the box. Any pointers would be appreciated!

**Comment by bebraw** [comment]
Hi,

You can see the current logic [here](https://github.com/bebraw/reactabular/blob/master/src/sort_column.js). It defaults to lodash `sortByOrder`. I can accept a PR against the `dev` branch that allows to replace that.

If you need something fast, you can override the logic completely as Reactabular has been decoupled from it. You might need just a custom `sort` function.

**Comment by damassi** [comment]
Thanks!
