### ISSUE TITLE
sort_column.js wipes out all header classes

### ISSUE THREAD

**Issue by dcpf** [bebraw/reactabular#108]
Reactabular sorting is managed by the sort-asc and sort-desc classes on the column header, and the code in sort_column.js sets these as necessary. However, in doing so, it wipes out all other classes set on the column. So if we want to set our own classes, they get removed whenever a sort is performed. The code in question is:

module.exports = function (columns, column, done) {
    columns.map(function (col) {
        col.classes = {};
        return col;
    });

    column.sort = column.sort === 'asc' ? 'desc' : 'asc';
    column.classes = {
        'sort-asc': column.sort === 'asc',
        'sort-desc': column.sort === 'desc'
    };

    done({
        sortingColumn: column,
        columns: columns });
};

This should be changed to:

module.exports = function (columns, column, done) {
    columns.map(function (col) {
    	delete(col.classes['sort-asc']);
        delete(col.classes['sort-desc']);
    });

    column.sort = column.sort === 'asc' ? 'desc' : 'asc';
    column.classes['sort-asc'] = column.sort === 'asc';
    column.classes['sort-desc'] = column.sort === 'desc';

    done({
        sortingColumn: column,
        columns: columns });
};

Thanks.

**Comment by bebraw** [comment]
Great idea. Do you want PR against `dev` or should I patch it?
