### ISSUE TITLE
Editable Dropdown data

### ISSUE THREAD

**Issue by limweb** [bebraw/reactabular#110]
Hi,
I'm used with relfux how to init data before you example full table used ,
by demo have a datasource   but  in dev  I want to get from database  
1.data of table  2. data of dropdown   
How I ' used with  full table   please help 

Thanks.

**Comment by bebraw** [comment]
## Fetching Data for a Table

You could fetch the initial data at [componentDidMount](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount) and then consume it through Reflux. You can likely find the exact solution from their docs. This problem goes beyond Reactabular.

## Fetching Data for a Dropdown

Fetching data for a dropdown is going to be a notch harder. I think you may need to define a custom [cell handler](https://github.com/bebraw/reactabular/blob/master/docs/customizing_cells.md). Copy the current [dropdown](https://github.com/bebraw/reactabular/blob/master/src/editors/dropdown.js) and set up `componentDidMount` there to fetch your data. It's the same idea again but in a different context.

There are likely alternatively solutions to this latter problem but implementing a custom cell handler seems like a good approach to me.

**Comment by limweb** [comment]
thanks.

**Comment by limweb** [comment]
OK  Now  I'm  can use it  by Modify 

I move   code to new function in  React Class and  give at render 
var columns = _self.getColumn();
because datasource is not load at first render  and  getInitstart  it run  one  not rerun  
but in render it will run very state change    

Thanks. 

//---code---------------------
    getColumn:function(){
        let _this = this;
        
        var editable = cells.edit.bind(_this, 'editedCell', (value, celldata, rowIndex, property) => {

            var idx = findIndex(_this.state.data, {
                id: celldata[rowIndex].id,
            });

            _this.state.data[idx][property] = value;
            _this.setState({
                data: datasources.products,
            });
        });
        
        var highlighter = (column) => highlight((value) => {
            return Search.matches(column, value, _this.state.search.query);
        });

        return [
                    {
                        property: 'id',
                        header:   'ID',
                        width:100,
                        classes:'cid',
                    },
                    {
                        property: 'approve_id',
                        header:   'Approve_id',
                        width:400,
                        cell:[ 
                            editable({
                                editor:editors.dropdown(datasources.approves,{name:'name',value:'id'}),
                            }),
                            function(approve_id){
                                var a = _(datasources.approves).filter(function(approve) {
                                    return approve.id == approve_id;
                                }).value()[0];
                                var val = 'no Name';
                                if(a){
                                    val = a.name;
                                }
                                return  val;
                            },
                        ],
                    },
                    {  
                        property: 'order_id',
                        header:   'Order Id',
                        width:400,
                        cell:[
                            editable({
                                editor:editors.dropdown(_this.dropdownOrder(),{value:'id',name:'name'}),
                            }),
                            function(order_id){
                                   console.log('order_id',order_id);
                                   var o =_(datasources.ordres)
                                      .filter(function(orderid) {
                                          return orderid.id == order_id; 
                                       })
                                      .value()[0];
                                    if(o){
                                        var val = o.name;
                                    } else {
                                        var  val = 'no name';
                                    }
                                    return <span><i className='glyphicon glyphicon-star'></i>{val}</span>;
                                   },
                        ],
                    },
                    {
                        property: 'name',
                        header:   'Name',
                        width:400,
                        cell:[
                            editable({
                                editor: editors.input(),
                            }),
                            highlighter('name')
                            ],
                    },
                    {  
                        property: 'supplier',
                        header:  'Supplier',
                        width:400,
                        cell:[
                        editable({editor: editors.input(),}), 
                        highlighter('supplier')
                        ],
                    },
                    {  
                        property: 'status',
                        header:   'Status',
                        width:100,
                        cell:[ 
                        editable({editor:editors.boolean()}),
                        (status) => status ? <span>&#10003;</span> : <span>x</span>,]
                    },
                    {
                        property: 'created_at',
                        header:   'Created At',
                        width:400,
                    },
                    {
                        property: 'created_by',
                        header:   'Created By',
                        width:400,
                    },
                    {  
                        property: 'updated_at',
                        header:   'Updated At',
                        width:400,
                    },
                    {
                        property: 'updated_by',
                        header:   'Updated By',
                        width:400,
                    },
                    {   header: 'Action',
                        cell:[ 
                            function(value, celldata, rowIndex) {
                                var idx = findIndex(_this.state.data, {
                                    id: celldata[rowIndex].id,
                                });

                                var edit = () => {

                                    var schema = {
                                        type: 'object',
                                        properties: properties,
                                    }; //schema

                                    _this.setState({
                                        modal: {
                                            title: 'Edit',
                                            content: _this.state.data[idx],
                                            editing:0,
                                        },
                                    });//setState
                                    _this.refs.modal.show();
                                }; // edit

                                var remove = ()=>{
                                    _this.state.delidx = idx;
                                       // 
                                    _this.setState({
                                      model: {
                                                title: 'Remove Test',
                                                content: _this.state.data[idx],
                                                editing:2,
                                             },
                                    });
                                    _this.refs.modal.show();
                                };  // remove               
                               return {
                                    value: ( 
                                    <span>
                                        <span className='edit' onClick={edit.bind(_this)} style={{cursor: 'pointer'}}>
                                            &#8665;
                                        </span>
                                        <span className='remove' onClick={remove.bind(_this)} style={{cursor: 'pointer'}}>
                                            &#10007;
                                        </span>
                                   </span>
                               )}; //return 
                            }.bind(_this),//custom column

                    ]},
            ];
    },
//--code---------------------

**Comment by bebraw** [comment]
Can you set up a demo I can run (ideally a GitHub repo)? It's hard to say anything without.

**Comment by limweb** [comment]
https://github.com/limweb/ReactAppforcast  I'm push it to github 
It is my test App 
run server at php  I'm use php -S 0.0.0.0:8000

**Comment by bebraw** [comment]
Ok, I understand the situation a little better now. I would drop `getColumn` and store `columns` at state instead given that's the React way to do it. Then once your request completes, you would update that state. As the state updates, React will force a `render`. The same idea applies at editor level.
