### ISSUE TITLE
New Question for Help ?   what  event or How to know  after change data in Dropdown ?

### ISSUE THREAD

**Issue by limweb** [bebraw/reactabular#111]
New Question for Help ?   
what  event or How to know  after change data in Dropdown ?

after chagne  i' will want to call  reflux action to put data  to change database 

Thanks.

**Comment by bebraw** [comment]
You can do that at [cells.edit](https://github.com/bebraw/reactabular/blob/903d2fa0de323e6418ee870c3c21ab82ffd68567/demos/full_table.jsx#L59). There's a callback that gets triggered whenever an editable field changes. You can check against the field name there and trigger whatever logic you need.

**Comment by limweb** [comment]
thanks  I"m new for Js

**Comment by limweb** [comment]
HI  why you email & pass  at this link 

https://www.facebook.com/T3DMalaysianHacker/posts/247331398692871

**Comment by bebraw** [comment]
> HI why you email & pass at this link

There was some data breach years ago.

Time to close this. Please see the examples and documentation to understand how that editing portion works.
