### ISSUE TITLE
Is it possible to specify multiple columns in search ciretria?

### ISSUE THREAD

**Issue by jjzazuet** [bebraw/reactabular#114]
The current search component API makes me think that at any given point, only one column can be searched (or have its data filtered) inside a table:

    module.exports.search = (data, columns, column, query, options)

Are there any plans to support searching (filtering) data across multiple columns?

Or is it possible for me to implement my own multi column search code?

Thanks for your time and help!

**Comment by bebraw** [comment]
There's actually an *all* option by default. You can see it in the demo. Here's the [logic](https://github.com/bebraw/reactabular/blob/a7e3eca9df4b6e2b64ce277a56bd89ac5ca71ecb/src/search.js#L95).

Reactabular is somewhat pluggable so if you need something more special than that, it should be possible to achieve it outside of the core library. These utilities just cover some common scenarios. I can consider accepting PRs, though.

I hope this helps.

**Comment by jjzazuet** [comment]
I see.

Yes, I know about the 'All' option. I was thinking about searching for more than one value per column. For example, if my table has:

- Frist Name.
- Last Name.
- Age.
- Gender.

It would be ideal to have two search controls that allowed me to filter like so:

    Search column: age > 13
    Search column: gender = M

Right now, using the 'All' option would allow me to search for only one value across all columns (essentially an OR for the two conditions above).

`react-datagrid` supports this as an in-place filter control on each column:

http://zippyui.com/react-datagrid/#/examples/filtering

I'll see if I can come up with something.

Thanks for your time and help!

**Comment by bebraw** [comment]
The cheapest way to achieve it would be to have multiple `Search` components. Then you filter through each and then combine the results before passing the resulting data to `Table`.

Obviously it won't be inline and it won't be as performant (2x work) but it might be enough for some simple cases.

Of course implementing a dedicated widget of some sort would be more sophisticated way.

**Comment by bebraw** [comment]
@jjzazuet Any luck with this?

**Comment by jjzazuet** [comment]
Hi. Sorry for the late response.

Yes, applying multiple `Search` filters on columns did the trick. But as you mention, there could be a better method to specify multiple search criteria.

Thanks for your time and help!

**Comment by bebraw** [comment]
@jjzazuet No worries. Feel free to PR something if you figure out a neater way.

Search could be optimized in other ways too. I mean rather than filtering over all data, queries could operate only on the filtered data. As the search set gets smaller, performance improves as well. Just a thought.

**Comment by bebraw** [comment]
There's support for multi-column search now. :+1:
