### ISSUE TITLE
the best way to add a row

### ISSUE THREAD

**Issue by Ezekiah** [bebraw/reactabular#115]
Hi, I would to know the best way to add a row in the table, I know that I could do by doing a form and then update this.state.data but  i'd like to know if there is a built in way to do that.
Thanks

**Comment by bebraw** [comment]
[Table](https://github.com/bebraw/reactabular/blob/master/docs/table_definition.md) just expects `columns` and `data`. It doesn't care where those come from.

In the demo I use JSON Schema and a form library that works well with it. I expect you will have to do something similar depending on what kind of user interface you want.

**Comment by Ezekiah** [comment]
Yeah you're right.
Finally I just made a form with plexus-form and reused the properties variable. 
Thanks

**Comment by bebraw** [comment]
Cool. Note that [react-json-editor](https://github.com/ismaelga/react-json-editor) is a maintained version of that library. I should port the example to that.

**Comment by Ezekiah** [comment]
Yes I used react-json-editor.
Thanks for your great module.
