### ISSUE TITLE
Turn off sorting 

### ISSUE THREAD

**Issue by jphamilton** [bebraw/reactabular#118]
It would be nice to be able to turn sorting off for certain columns. For instance, on your demo page, the column with the edit controls in it is sortable, which really doesn't make sense. I have something similar (checkbox select row) and I don't want that column to be sortable.

**Comment by bebraw** [comment]
Yeah, makes sense. Maybe it would make sense to flag the columns to skip or something. A proposal is welcome.

**Comment by jphamilton** [comment]
A "sortable" property in the column definition that defaults to true (to keep current compatibility) is what I was thinking.

**Comment by bebraw** [comment]
@jphamilton Sounds good. Want to do a PR?

**Comment by eviltoylet** [comment]
This is probably a good incremental step. However, if you're up for tackling it, I would suggest you introduce a comparator per column which would be able to generate more complex sort orders. The sorting algorithm should be stable, so that a no-op comparator would give the correct results.

**Comment by jphamilton** [comment]
@eviltoylet, @bebraw  Sorry, I've been out of town. I will try to tackle a PR. I think we are talking about 2 different issues, though. I just want to turn sorting on/off and it sounds like you want to be able to create more complex sorts. Or am I missing something?

**Comment by bebraw** [comment]
@jphamilton No worries. PR based on your need and we go from there. :+1:

**Comment by bebraw** [comment]
This has been solved in the current beta. You literally attach sorting functionality per column making the problem disappear.
