### ISSUE TITLE
How to fix column in the left and another scroll

### ISSUE THREAD

**Issue by limweb** [bebraw/reactabular#119]
How to fix column in the left and another scroll

Thanks.

**Comment by bebraw** [comment]
Can you give a visual example? I'm not exactly sure what's needed.

**Comment by limweb** [comment]
![2015-12-28 15_02_25-microsoft excel - template forcast oct 2015](https://cloud.githubusercontent.com/assets/602579/12015786/19cda6dc-ad74-11e5-9448-ce78bcc80e7d.png)

like this  thanks

**Comment by bebraw** [comment]
Is it fixed so that when you scroll horizontally, the column will remain visible while the rest scrolls below it?

**Comment by bebraw** [comment]
Can you set up an example based on pure HTML and CSS (possibly JS if needed)? That would help me to understand how to map the functionality to Reactabular.

**Comment by bebraw** [comment]
I think you might be able to pull of fixed header quite easily in the current beta. That fixed row would be hard. Give it a go.
