### ISSUE TITLE
sorting documentation incorrect

### ISSUE THREAD

**Issue by goldensunliu** [bebraw/reactabular#120]
for some reason sorting stopped working for me.

in the sort documentation in https://github.com/bebraw/reactabular/blob/master/docs/sorting_table.md

one should be able to create a table like:
```jsx
<Table columns={columns} data={paginated.data} header={header} />
```
where header is
```js
header: {
    onClick: (column) => {
        sortColumn(
            this.state.columns,
            column,
            this.setState.bind(this)
        );
    },
}
```

what I have noticed is that the `onClick` function never gets called. also I wasn't able to find in the source where `props.header` is ever used: https://github.com/bebraw/reactabular/search?utf8=%E2%9C%93&q=.header

Am I missing something?

**Comment by bebraw** [comment]
`onClick` should get mapped to a prop.

Can you try setting up a demo for me to study? You can for instance fork this repo and tweak the official demo. Whatever is the easiest for you.

**Comment by goldensunliu** [comment]
@bebraw in the demo, we are using the prop `columnNames' instead of 'header':
https://github.com/goldensunliu/reactabular/blob/master/demos/full_table.jsx#L286

if instead of `columnNames={this.columnFilters}` we replace it with `header={this.state.header}`, nothing seem to work

**Comment by goldensunliu** [comment]
looks like the doc in https://github.com/bebraw/reactabular/blob/master/docs/sorting_table.md
should be
```jsx
<Table columns={columns} data={paginated.data} columnNames ={header} />
```
correct me if I am wrong

**Comment by bebraw** [comment]
@goldensunliu Yeah. Want to do a PR to fix that?

**Comment by goldensunliu** [comment]
accordingly to this change. https://github.com/bebraw/reactabular/commit/19b3501aff0f0cd269144f3d97f7422195309be3

is the intention to change `header` to `columnNames`? i.e should we change the documentation to reflect that

**Comment by bebraw** [comment]
@goldensunliu Yup. The documentation needs a fix.

**Comment by goldensunliu** [comment]
@bebraw PR is ready to go, dawg.

**Comment by bebraw** [comment]
Thanks!
