### ISSUE TITLE
Loop on each rows cells and call a function on it

### ISSUE THREAD

**Issue by Ezekiah** [bebraw/reactabular#124]
I'm trying to implement the multiselect feature and when I click on "select all", I would like to loop on each rows of the current page and select them.
I tried to see if there are refs for rows but there are not presents.

**Comment by bebraw** [comment]
I think you need to go through the column definition of `data`. When you "select all", set the column selection state for each to selected (could be boolean). Your cell rendering should take this into account.

**Comment by Ezekiah** [comment]
Oh yes I think I got it, I try to do as you said.

**Comment by Ezekiah** [comment]
Could you explain to me what you by column definition of data ?

**Comment by bebraw** [comment]
I can see two options in your [current code](https://gist.github.com/Ezekiah/c8294613aef0f9f4c8d0). Merge your selection state to that `data: data` portion or alter `selected_rows` when you trigger "select all". If you do latter, you'll need to perform a lookup that gives the value for that `input` at your `cell` renderer. I expect both ways will work.

The problem in your current implementation is that you haven't connected the selection state to display logic like this. It shouldn't matter how you manipulate the selection state (directly, through "select all", or through some other way). It will always rely on that same data to figure out how to display itself for each column cell.

**Comment by Ezekiah** [comment]
I attached selected to all my data and I set all data selected column to true/false when I select all, when I click on one checkbox I just change one row in the data ans setstate also.
However I would like to selectall only the data of the current page, so I should recover the current page of the paginator, knowing the number of product and the page I'll be able easily to do so. I'm going to add a ref on the paginator and see its api to see if I can retrieve the info.

**Comment by bebraw** [comment]
@Ezekiah Maybe it would make sense to do id (row object, not row id) -> selected state lookup? Then when you change pages, it should pick it up. If it's tied to something else, that could lead to trouble.

**Comment by Ezekiah** [comment]
What do you mean, can you give me an example ?

**Comment by bebraw** [comment]
I would do something like this at `cell: function(value, celldata, rowIndex)`:

```javascript
var selected_rows = this.state.selected_rows;

var is_selected = selected_rows[celldata.id]; // not sure of your schema, do a lookup here anyhow

...

<input ... value={is_selected} />
```

Then when you select, you do something like this:

```javascript
...

selected_rows[id] = true; // or false if you deselect

...
```

This should be enough as it decouples selection from a page. If a page changes, the selection remains. This also respects sorting etc.

**Comment by Ezekiah** [comment]
Ok I did as you said and its working perfectly, thanks.
Do you know why I get this warning "Warning: Only strings and numbers are supported as <option> children." when I put a column header as <input type="checkbox" ref='selectAll' onClick={this.selectAll} style={{width:'20px'}}/>

    columns: [

				  {
					  property: 'selected',
					  header: <input type="checkbox" ref='selectAll' onClick={this.selectAll} style={{width:'20px'}}<input type="checkbox" ref='selectAll' onClick={this.selectAll} style={{width:'20px'}}/>/>,

**Comment by bebraw** [comment]
> Do you know why I get this warning "Warning: Only strings and numbers are supported as children." 

You have `input` inside `input`. You should restructure your markup to avoid this scenario.

**Comment by Ezekiah** [comment]
I did a spelling mistake, even with only one input I got the warning.

**Comment by bebraw** [comment]
@Ezekiah Ok. I understand the problem now. It's that search `select`. I'll add a little check there against this.

**Comment by Ezekiah** [comment]
Do I need to wait a new version to resolve it, or theres a fix ?

**Comment by Ezekiah** [comment]
Ok thanks i download the fix
