### ISSUE TITLE
Translate search component

### ISSUE THREAD

**Issue by Ezekiah** [bebraw/reactabular#130]
In the search select input there is the choice "All", I would like to change it, how can I do that because I would like to translate it please.

**Comment by bebraw** [comment]
Yeah, that's hardcoded at the moment. Good point!

What if we exposed it through a prop? That would seem like a good starting point. Maybe you could have something like `i18n` prop that would accept an object containing `all`. Then you would get:

```javascript
<Search i18n={{all: 'Kaikki'}} ... />
```

Do you want to PR this? It's a fast tweak for me to do, though, if this sounds ok to you.

**Comment by bebraw** [comment]
@Ezekiah `0.11.1` contains the fix. It uses the API I proposed above. So pass an object and you are all good.
