### ISSUE TITLE
Inline editing a row launch a past data state

### ISSUE THREAD

**Issue by Ezekiah** [bebraw/reactabular#131]
When I use the boolean editor on my row, the list refresh however it loads a past data state, do you know how I can solve it  please ? 
Maybe it's a problem coming from my own code, I'm pretty sure of that :s

I have my gist here : https://gist.github.com/Ezekiah/c8294613aef0f9f4c8d0, if someone can help me please.

**Comment by bebraw** [comment]
Can you set up a standalone example for me to study? Easier to debug what's going on. Simplify as much possible.

**Comment by bebraw** [comment]
I'm closing this as there isn't enough information to debug properly.

Feel free to open again if you get a simple standalone example online. You could for instance fork this project and tweak the example.
