### ISSUE TITLE
Give a warning if `rowKey` is missing

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#135]
As it helps with performance, it would be nice to warn if it's missing.

**Comment by maxkorp** [comment]
Adding .required to the proptype should be sufficient.

**Comment by sourabhlk** [comment]
Hi can u explain more on this, facing warning issues

**Comment by bebraw** [comment]
@sourabhlk It depends on your data. If you have some id value, set the key to point to it. There are plenty of examples in the documentation.
