### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by tBaxter** [bebraw/reactabular#140]
Cannot get basic example working. Seeing ReferenceError: Unknown plugin "syntax-object-rest-spread"

**Comment by bebraw** [comment]
Can you provide more info? What sort of system (Node version, npm version), what commands?

**Comment by tBaxter** [comment]
It appears to be a Babel issue, wanting that plugin and transform-object-rest-spread. I had to do this for both plugins: https://babeljs.io/docs/plugins/syntax-object-rest-spread/

**Comment by bebraw** [comment]
Those should be project `devDependencies`. Maybe it's a version issue. I should bump the versions anyway.

**Comment by tBaxter** [comment]
I think I've got it working on my end. Feel free to close if you like.

**Comment by bebraw** [comment]
Ok, I'll bump those deps and close then. :+1:
