### ISSUE TITLE
Allow passing table caption

### ISSUE THREAD

**Issue by tBaxter** [bebraw/reactabular#142]
Could you add options to pass in additional table structures such as caption, col and colgroup? 
In particular, I think caption would be a solid addition.

Ref:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
* http://webaim.org/techniques/tables/data

**Comment by bebraw** [comment]
You can likely achieve a lot of that with the current hooks. You could add a [custom header](https://github.com/bebraw/reactabular/blob/master/docs/customizing_header.md) for example. I think you might be able to do those `col` things and `caption` too there.

**Comment by tBaxter** [comment]
that's not super clear. If I'm defining the custom head in columnames, then what's header doing?

**Comment by bebraw** [comment]
Check the second example at the [demo site](https://bebraw.github.io/reactabular/). Essentially it's doing an override like this:

```jsx
columnFilters() {
    var headerConfig = this.state.header;
    var columns = this.state.columns;
    // if you don't want an header, just return;
    return (
        <thead>
            <ColumnNames config={headerConfig} columns={columns} />
        </thead>
    );
}
```

and then `columnNames={this.columnFilters}`.

I know it's not that cool. Too obscure. That's why I'll want to move to a context based API eventually. See #109 for a possible design. Comments welcome.

**Comment by bebraw** [comment]
@tBaxter Can you take a look at the current beta? See #148 for further details.

**Comment by bebraw** [comment]
I guess it's safe to close this now. Please keep up with the betas. 👍
