### ISSUE TITLE
Search not working correctly with nested data

### ISSUE THREAD

**Issue by tBaxter** [bebraw/reactabular#143]
Due to some oddities with my json, I'm extracting some information like so:

var columns = [
    {
        property: "foo",
        header: 'First Name',
        cell: (v) => (v.FirstName),
    },
    {
        property: 'foo',
        header: 'Last Name',
        cell: (v) => (v.LastName),
    },
    {
        property: 'Site',
        header: 'Site',
    },
    {
        property: 'foo',
        header: 'Date of Birth',
        cell: function(value) {
            var date = new Date(value.DOB);
            return date.toLocaleDateString();
        }
    },
];

Using the Search component, it is only working from the property, so it is not building the select correctly:

<select>
<option value="all">All</option>
<option value="foo">First Name</option>
<option value="Site">Site</option>
</select>

**Comment by bebraw** [comment]
Can you set up a standalone example (GitHub repo)? Easier to study.

Searching against nested data might require some custom logic.
