### ISSUE TITLE
postinstall script fails on node 0.10.x

### ISSUE THREAD

**Issue by Gudahtt** [bebraw/reactabular#144]
The postinstall script fails when installing on node 0.10.x. I've tested this on versions `0.10.32`, `0.10.33`, and `0.10.45`. I've also tested this with npm versions `2.15.1` and `3.9.5` on each of those node versions.

It looks like it's because devDependencies aren't installed until *after* the postinstall script, so the `sync-exec` dependency isn't available when `lib/post_install.js` is run. Details on that here: https://github.com/npm/npm/issues/10366 and https://github.com/npm/npm/issues/4134

I'm not sure what can be done about this. Perhaps support for 0.10.x should be dropped for now, until a solution is found? Or maybe the `/lib/post_install.js` script can be modified to not require `execSync`. I'm not sure how else this could be solved.

**Comment by bebraw** [comment]
> I'm not sure what can be done about this. Perhaps support for 0.10.x should be dropped for now, until a solution is found? Or maybe the /lib/post_install.js script can be modified to not require execSync. I'm not sure how else this could be solved.

I don't have a great interest in supporting Node 0.10 given it's so old. I don't mind dropping it given it appears to be problematic.

If you can figure out a way to drop `execSync` I guess that would be the best solution. `/lib/post_install.js` is a hack at best. 😞

**Comment by Gudahtt** [comment]
Yeah, I can't see any particularly nice solution. You could inline `execSync` or some equivalent function, but that'd be even more of a hack.

One option would be to transpile *before* publishing, rather than after. My impression from the `npm` folks is that they'd like to deprecate `postinstall` altogether because they want to prevent/discourage library authors from installing things aside from the library itself.

One option would be to transpile *before* publishing, rather than after. My impression from the `npm` folks is that they'd like to deprecate `postinstall` altogether because they want to prevent/discourage library authors from installing things aside from the library itself.

I haven't looked into it a whole lot, so perhaps there's a good reason not to do it that way. But that would solve this problem, and would make the package easier to install in general. Thoughts?

**Comment by bebraw** [comment]
@Gudahtt I actually transpile before publishing to npm. The script is meant only for those users that use the git version for a reason or another.

**Comment by Gudahtt** [comment]
Ah OK, thanks. I knew I had to be missing something - I've seen other libraries do this as well. Hmm.

**Comment by bebraw** [comment]
@Gudahtt I guess dropping Node 0.10 would be the easiest way out. Just need to set up `engines` field and that's it. Btw, see [my API prototype](https://github.com/bebraw/reactabular/tree/context-api) (esp. demo). If you have thoughts on that, comment at #109. This is a good time to get features in.

**Comment by Gudahtt** [comment]
@bebraw Sure thing! Will do.

I think I might have a solution for the `postinstall` problem, without dropping support for `0.10.x`. Using `spawn` instead of `execSync` should do the trick. I can create a PR.

**Comment by bebraw** [comment]
@Gudahtt Ok, cool. That would be great.

**Comment by Gudahtt** [comment]
Great, thanks! Problem solved.
