### ISSUE TITLE
Fixed-width columns after initial load (filtering)

### ISSUE THREAD

**Issue by isaachinman** [bebraw/reactabular#146]
Really like this component and have put it to use in a current project. Was able to get filtering working very easily. 

However, due to the nature of my content (and I'd imagine nearly anyone else's), the column widths change as I filter and certain content is removed. This makes for a jarring experience, as content is jumping around with every keydown event.

Is there currently any way to capture a column's width after initial render and save it? I would think this should be default behaviour, as any filtered data is a subset of the whole, and the table should always be in orientation to support the entire dataset.

For an example, you can check [your own docs](https://bebraw.github.io/reactabular/). On the first table, if you type `b` into the search input, you will see what I mean.

**Comment by bebraw** [comment]
Yeah, that's a good question.

I'm actually redoing the API right now (#109). I'll push a prototype in a bit so you can have a look. Maybe we can get some kind of hooks there to capture the initial widths.

**Comment by isaachinman** [comment]
Sounds good. 

It's a bit more complicated than just initial width - if you use filtering and column sorting together, there is the possibility of a column gaining width due to the pseudo-element arrows. So it'd probably be more versatile to create some "capture column widths" method and reuse as needed.

**Comment by bebraw** [comment]
Here's [the new API](https://github.com/bebraw/reactabular/blob/3df147cf27496fd92850520f383b9fd0cb6b67e7/demos/full_table.jsx#L245).

It's still in flux so if you can see how the hooks would fit in there, let me know. We can perhaps leverage React lifecycle methods here.

**Comment by isaachinman** [comment]
Is there no current way of passing CSS attributes to columns? Classes aren't going to work in this case.

**Comment by bebraw** [comment]
@isaachinman The column definition has a `cell` handler just for this purpose. You have to define it per cell to attach a CSS attribute per each column, though. Perhaps it would make sense to expand the API definition to make this easier. Good point.

**Comment by isaachinman** [comment]
I see, was able to get it working with fixed widths like this:

    cell: (v) => ({
      value: v,
      props: {
        width: 500
      }
    })

Not sure how to get cell width after it mounts. How often do these cells mount? On every table render? Sorry, just having a hard time seeing how these cells fit in the table lifecycle. If they already have props, it appears they already have some kind of lifecycle?

But I'd think if they are re-rendering all the time, fixed-width data will have to be stored at a higher level.

**Comment by bebraw** [comment]
> Not sure how to get cell width after it mounts. How often do these cells mount? On every table render? Sorry, just having a hard time seeing how these cells fit in the table lifecycle. If they already have props, it appears they already have some kind of lifecycle?

They go through `render()`, yeah. A little inefficient but flexible. 👍 

I have to think about lifecycle in detail. Ideally this is something we would set only on mount I think.

**Comment by isaachinman** [comment]
Okay, let me know if you think of a solution. I'm happy to implement something and submit a PR.

**Comment by bebraw** [comment]
@isaachinman You can actually pass a React component to `cell`. That gives you access to its lifecycle if you want. Maybe that's the key. No additional API needed. This is more of an optimization anyhow.

**Comment by isaachinman** [comment]
Yes, that was my initial thought as well.

**Comment by isaachinman** [comment]
Just in case anyone else comes across this and wants a quick solution, this is what I hacked together.

In your column definition, add a class:

    const columns = [{
        property: 'name',
        header: 'Name',
        cell: (v) => ({
          value: v,
          props: { className: 'fixed-width' }
        })
      }]

And then in your `componentDidMount` for whatever component has the table within it:

    let fixedWidthCells = document.querySelectorAll('td.fixed-width')
    Array.prototype.forEach.call(fixedWidthCells, (el, i) => {
      el.style.width = el.offsetWidth + 'px'
    })

I'm sure there are much more elegant ways to do this than manipulating the DOM outside of React, but I needed a quick fix and this works fine.

**Comment by bebraw** [comment]
@isaachinman that's a cool idea. i wonder if a ref would work here. then you would avoid `document.querySelectorAll`

**Comment by isaachinman** [comment]
@bebraw Probably so. 

Also, I've made a slight change above. I'm now affixing the `fixed-width` class to headers, not body cells. This is to prevent code repetition in each column cell, and also to maintain widths even if filtering causes the table to be empty.

**Comment by bebraw** [comment]
You could do something like this with the new API (still in flux):

```jsx
<Table.Header
  header={{
    className: 'fixed-width'
  }}
>
```

Would that help?

I could also provide a more specific API and accept a function (`(column) => ({className: 'fixed-width'})`) for better customization. This could be a good idea anyway.

**Comment by isaachinman** [comment]
Sure, as you want. As long as the `th` nodes get an explicit width set after the table is injected, everything should work fine. There is another problem with hidden tables (eg tabs), but that's another issue entirely.

**Comment by bebraw** [comment]
@isaachinman I released a beta. See #148. Do you want to try implementing the idea there? The API should be more flexible now so you can customize it per header and so on. 👍

**Comment by isaachinman** [comment]
Unfortunately I'm super busy right now and don't have time to produce a proper contribution. Might have more time in about two weeks. 

Unless you have another idea, I guess the simplest way to do this is just pass a React component into the header that explicitly sets its width in `componentDidMount`.

**Comment by bebraw** [comment]
No probs. I guess I'll try setting up a little demo. :)

**Comment by isaachinman** [comment]
What's the protocol for PRs on this project? Do you think this kind of behaviour should be default, or an additional option? It's perfectly "responsive", just not if screen width changes after the component mounts.

**Comment by bebraw** [comment]
Hi,

I guess we should decide how it could go in. Ideally it would be possible to plug in the feature through an extension mechanism. There are several hooks just for this and I can implement more if needed. Going through a hook would force me to keep the core flexible and that's a good thing.

You could try to set up a PR and we can discuss further there. I have some smaller changes in mind for the source but it's definitely more stable than a couple of days ago.

**Comment by bebraw** [comment]
@isaachinman I added `header.component` and `cell.component` hooks. See the [API docs](https://bebraw.github.io/reactabular/#/table/column-definition). I think we might be able to achieve what you want through those perhaps.

**Comment by isaachinman** [comment]
Yup, definitely. Can just create a super simple React component that sets its own width explicitly after mounting. 

The question is if you want this as default or built-in optional behaviour, otherwise it's up to the user to define such a component.

**Comment by bebraw** [comment]
This would be a perfect demo (`docs/tables` for code + `docs/examples` for the text part). I've implemented a lot of useful bits there. So if you want to PR there, that would be great.

Maybe we'll end up with some Reactabular wrapper that contains more functionality.

**Comment by isaachinman** [comment]
Ah, good point. I'll do that then. Cheers!

**Comment by isaachinman** [comment]
@bebraw You'll see I just submitted a PR, #159. It was obviously quick work, so let me see if you see any issues.

**Comment by bebraw** [comment]
@isaachinman Awesome! I added some comments here and there. Good work. 👍

**Comment by bebraw** [comment]
Forgot to close this at merge. Thanks again!
