### ISSUE TITLE
Sorting on columns that have object data

### ISSUE THREAD

**Issue by skosch** [bebraw/reactabular#149]
Right now, sorting works purely on `property`, and thus relies on the data rows consisting of comparable scalars. This mechanism falls apart when the columns are fed objects instead (displayed via a `cell: ...` function), because `orderBy` just sees said objects and doesn't know how to sort them.

Enhancement idea: provide a custom version of `orderBy` out of the box that allows the user to specify a function per column that is applied to the data before sorting. As a fragile prototype, here's how I'm sorting my data right now in my render function:

```javascript
    let sortOrder = this.state.sortingColumn.sort === 'asc' ? 1 : -1;
    let property = this.state.sortingColumn.property;
    let sortProperty = this.state.sortingColumn.sortProperty; // user-defined function
    if (sortProperty) {
      data.sort((a, b) => {
        return sortProperty(a[property]).localeCompare(sortProperty(b[property])) * sortOrder;
      });
    } else {
      data.sort((a, b) => {
        return a[property].localeCompare(b[property]) * sortOrder;
      });
    }
    // hand data to the Table
```
... it's not the greatest, but it works – maybe it inspires you to come up with a friendlier and more robust API?

**Comment by bebraw** [comment]
What if we separated data formatting and data extraction? This would mean we would get an additional field where you would dig the cell data value. This would allow us to dig the data before highlighting/searching/etc. and might go a long way towards solving the underlying problem.

I would love to extract the search bits to a component of its own btw. Doing this would definitely help in achieving that goal.

**Comment by skosch** [comment]
Sounds good to me!

If/when you build a search component though, it'd be nice if you could make it (optionally) composable in some way, so users can use their own `TextField` components etc. inside of it.

**Comment by bebraw** [comment]
Good point! I'll do the API tweak first and think about search.

**Comment by skosch** [comment]
Sorry, coming back to this – in what way would this overlap with/obviate the current `search` field?

**Comment by bebraw** [comment]
> Sorry, coming back to this – in what way would this overlap with/obviate the current search field?

It's cool.

Let's say we do something like `data: ({ value }) => value.nested` to deal with nested data. We are going to need a way to transform the initial data so that it digs the data for `search`. That feels like a function Reactabular should provide making it a core functionality.

The remainder, `Search` and the associated methods, can live outside of the core. The next release probably doesn't do the split. The functionality just feels something more generic as the only Reactabular specific aspect happens to be the data format it uses.

**Comment by skosch** [comment]
Yep, that's what I meant. `Search.search` currently uses `col.search` if it's present (and `property` otherwise); sorting works purely on the `property` AFAIK.

Couldn't we just change both to use (approximately) `col.data({value: row[property], cellData: row}) || row[property]` for whatever they do?

I'm on beta2 right now, and both searching and sorting crashes because some of the data is nested, so this functionality would make a big difference :)

**Comment by bebraw** [comment]
@skosch I'll do a little prototype on data extraction and set up an example about nested search. That will go to beta3. We can go from there and figure this out. Thanks for the input!

**Comment by skosch** [comment]
To clarify, I was thinking of the `data` field (maybe we can find a better name?) as a function that returns a searchable/sortable string representation of what's in the cell, whereas `cell` still has access to the whole object (and `dataCell`, which is super useful) to render whatever pretty component the user wants it to. If we're not on the same page please explain!

**Comment by skosch** [comment]
Alright, looking forward to what you'll come up with! Thanks for being so responsive :+1:

**Comment by bebraw** [comment]
> To clarify, I was thinking of the data field (maybe we can find a better name?) as a function that returns a searchable/sortable string representation of what's in the cell, whereas cell still has access to the whole object (and dataCell, which is super useful) to render whatever pretty component the user wants it to. If we're not on the same page please explain!

That's the idea, yeah. Data extraction and formatting are going to be separate concerns. I need to think about the naming, good point.

**Comment by bebraw** [comment]
So here's what I'm thinking

```javascript
{
  property: 'dad',
  header: 'Dad',
  cell: ({ value }) => `id: ${value.id} , name: ${value.name}`,
  value: ({ value }) => value.dad,
},
```

`value` would literally extract the value if set. If not set, it will return the default. Any thoughts on the name?

**Comment by skosch** [comment]
Neat, that's just what I had in mind!

All I can think of are ugly monstrosities like `rawContent` or `scalarValue` or `comparable` ... calling it `value` may lead to confusion since in other places it refers to the entire data object. Hm.

**Comment by bebraw** [comment]
This is enough for now. We can change the name later after proving the idea. About done with the basic implementation. 👍

**Comment by bebraw** [comment]
@skosch I found a simpler solution. It was possible to do just `property: 'dad.name'` kind of declaration and avoid the naming issue. This incidentally happens to work with `orderBy` fixing this issue. Now also searching against nested data works. Included in beta3.

**Comment by skosch** [comment]
That's really neat (and should be documented!), but I still think there's value in your earlier proposal, since often enough the cells combine data from multiple nested fields, i.e. `` `${dad.firstName} ${dad.lastName}` ``, and we'd like to have that searchable too, no?

**Comment by skosch** [comment]
Oh boy, I'm already forgetting what I opened this issue for in the first place ... :flushed: 

Alright then!
