### ISSUE TITLE
Doesn't seem to work with RequireJS

### ISSUE THREAD

**Issue by eviltoylet** [bebraw/reactabular#15]
I was getting issues with using Reactabular with RequireJS. I'm not sure if this was a configuration problem on my part, or if it just doesn't play well with webpack.

```
Uncaught Error: Script error for: react/addons
http://requirejs.org/docs/errors.html#scripterror 
makeError (require.js:166)
context.onScriptError (require.js:1696)
```
```
requirejs.config({
    paths: {
      'reactabular': '/bower_components/reactabular/dist/reactabular'
    }
});
```

**Comment by bebraw** [comment]
@eviltoylet Can you try changing `config/webpack.common.dist.js` `'react/addons': 'react/addons'` to `'react/addons': 'react'?

**Comment by eviltoylet** [comment]
Yeah that works, but it doesn't seem like the correct thing to do. The package layouts for react are different in bower and npm.

Maybe this is what I need to do? But ... I don't actually know :P
```
requirejs.config({
    paths: {
      'react': '/bower_components/react/react',
      'react/addons': '/bower_components/react/react-with-addons',
    }
});
```

**Comment by bebraw** [comment]
Yeah, I understand better what's going on here now. Webpack will alias React as `react/addons` in our current build. In other words your config is correct and you can simplify it further:

```
requirejs.config({
    paths: {
      'react/addons': '/bower_components/react/react-with-addons',
    }
});
```

Now that I think of it, our current naming is correct. We depend on React with addons after all. The first part of Webpack config (`'react': 'react') is likely redundant. We shouldn't have any direct references to vanilla React anywhere given that breaks the tests (they end up with two instances of React).

**Comment by eviltoylet** [comment]
Yup, I'm going to close this as a non issue. Thanks!
