### ISSUE TITLE
Support `value` customization (aggregate values!)

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#150]
To quote @skosch:

> That's really neat (and should be documented!), but I still think there's value in your earlier proposal, since often enough the cells combine data from multiple nested fields, i.e. `${dad.firstName} ${dad.lastName}`, and we'd like to have that searchable too, no?

**Comment by bebraw** [comment]
I wonder if we should just leave this to the user space. It would be possible to perform this kind of operation on the data itself before it gets passed to Reactabular. If we integrate aggregate values, then it causes complications especially with sorting as then you need to perform a "normalization" step before pushing the values to an algorithm like `orderBy`.

Any thoughts?

**Comment by skosch** [comment]
That probably makes sense. The nice thing about `orderBy` sorting though is that it takes care of ascending/descending across multiple columns for you, and it's relatively robust to whatever data comes in (strings, numbers, undefineds, nulls, objects, etc.). I explicitly wouldn't want to "normalize" (i.e. flatten) my data before passing it to `orderBy`, because, well, I'd still like to have access to the nested attributes in my `cell` function later on. And so if we're leaving users to implement their own nested-data version of `orderBy` I think it'd be a nice gesture if at least a well-tested example were provided in the documentation for people to copy-paste and tweak to their needs.

**Comment by bebraw** [comment]
Providing a custom `orderBy` could work, yeah. That still leaves the issue of search, though. The earlier `value` solution worked well with that.

Even with nested property selectors (that `foo.bar.baz` thing) we could still provide access to the original data. It's just that `value` for default to the one pointed by the selector.

Maybe all of this makes more sense once I start decoupling the packages. As long as there are clear contracts between the core and the additional bits, it should work.

**Comment by skosch** [comment]
Well, in many (most?) cases the `foo.bar` properties will probably be enough for both search and sort purposes. If they aren't, we can let the user specify a function that is expected to return a string (or other comparable-kind type). If it's absent you can fall back via `||` on the `property`, no?

Alternatively to letting users write their own `orderBy`, reactabular could provide a wrapper à la:

```javascript
nestedOrderBy(data, columns, sortColumns) {
   flattenedData = data.map( /* apply value() functions, if any, to the data */);
   flattenedDataWithIndices = data.map( /* add an index field to each row */ );
   sortedFlattenedData = orderBy(flattenedDataWithIndices, columns, sortColumns);
   outputData = new Array(data.length);
   for (/* loop through sortedFlattenedData with i */) {
      outputData[sortedFlattenedData[i].index] = data[i];
   }
   return outputData;
}
```

**Comment by bebraw** [comment]
The search case isn't actually trivial. `Search.search` needs to output unflattened data so the surrounding logic doesn't break. So it needs to do some sort of lookup while keeping the original shape of the structure intact. I realized this while playing around with the ideas earlier. But that's just details. 👍

**Comment by bebraw** [comment]
I ended up implementing `value` field after all and it works quite beautifully. So I guess it's safe to close this then. The feature will make it to the next beta (due later today).
