### ISSUE TITLE
 Cannot resolve module 'expose'

### ISSUE THREAD

**Issue by bherrmann7** [bebraw/reactabular#152]
$ npm -version
3.9.3
$ npm install
$ npm start
...
ERROR in ./docs/index.jsx
Module not found: Error: Cannot resolve module 'expose' in /home/bob/reactabular/docs
 @ ./docs/index.jsx 1:0-18

**Comment by bebraw** [comment]
Thanks! I added the missing dependency. webpack-validator should definitely check for this...
