### ISSUE TITLE
Highlighting effecting wrong columns

### ISSUE THREAD

**Issue by bherrmann7** [bebraw/reactabular#153]
I presume the highlight should be restricted to the column searched....   am I mistaken?

Thanks!

![screen shot 2016-06-23 at 9 22 48 am](https://cloud.githubusercontent.com/assets/33614/16304618/3a018176-3924-11e6-8703-f5b811a547cc.png)

**Comment by bebraw** [comment]
Yeah, good catch. I'm currently doing some work around search so it's the perfect time to fix that. Thanks!
