### ISSUE TITLE
Error: React.createElement: type should not be null, undefined, boolean, or number

### ISSUE THREAD

**Issue by uneart** [bebraw/reactabular#156]
Hello everyone,

I am trying to implement Reactabular in my app but I always get the following errors:
```
React.createElement: type should not be null, undefined, boolean, or number. 
It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `UserTable`.
````
````
Uncaught TypeError: fn is not a function
```

First, I thought the problem was the data object I'm passing. But even after just integrating the sample data from the docs, I still get the errors. Do I maybe import Reactabular incorrectly? 

Here is my complete component code:
````
import React, { Component, PropTypes } from 'react';
import { Table } from 'reactabular';

const data = [
  {
    uid: 100,
    displayName: 'Adam',
    email: 'adam@test.de',
    lovesBeeGees: true
  },
  {
    uid: 101,
    displayName: 'Brian',
    email: 'brian@test.de',
    lovesBeeGees: false
  }
];

const columns = [
  {
    header: {
      label: 'Name'
    },
    cell: {
      property: 'displayName'
    }
  },
  {
    header: {
      label: 'E-Mail'
    },
    cell: {
      property: 'email'
    }
  }
];

export default class UserTable extends Component {
  render() {
    return (
      <div>
        <Table
          className="table table--compact table--cells user-table"
          data={data}
          columns={columns}
          rowKey="uid" >

          <Table.Header />
          <Table.Body />

        </Table>
      </div>
    );
  }
```

Any ideas how to solve this?

**Comment by bebraw** [comment]
The docs are for the [beta](https://github.com/bebraw/reactabular/issues/148). Make sure you install it through `npm i reactabular@beta9`. If this doesn't work, then there's something else going on.

I'll do a couple of betas still before pushing out a stable release. There are still some features to be developed. 👍

**Comment by uneart** [comment]
Oh damn. I should have thought of that. Completely solved the problem. Thanks for the quick reply!

**Comment by bebraw** [comment]
No problem. Thanks for testing the beta! Subscribe to that thread to keep up to date.
