### ISSUE TITLE
Can we benefit from `uncontrollable` approach?

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#17]
https://github.com/jquense/uncontrollable

**Comment by eviltoylet** [comment]
Reactabular already follows this pattern. Didn't provide a formatter? We'll just use a default one. However, this is a very simple thing to do and I don't think we need to adopt this dependency to do it. In practice we can just consult 'props' to see if things are there and use a sane default if it's not provided. The presence of the `tapsHash` in the code is suspicious to me. 

However, one thing that I did like is the use of `React.PropTypes`. :)

**Comment by bebraw** [comment]
> However, one thing that I did like is the use of React.PropTypes. We should definitely adopt that. :)

Yeah, let's leave this open for now till that gets resolved.
