### ISSUE TITLE
Make sure `sort_column` survives nulls

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#21]
@spincycle, Your attachment didn't make it through. Just curious to see how you solved this. :)

It's a good idea to add some null checks there anyway.

**Comment by spincycle** [comment]
data.sort(function(a, b) {
        var p1 = a[property] || "";
        var p2 = b[property] || "";
        if (p1.localeCompare) {
            return p1.localeCompare(p2) * column.sort;
        }
        return (p1 - p2) * column.sort;
    });

Apparently localeCompare doesn't like null but it's ok with empty string.
