### ISSUE TITLE
Add more robust test suite

### ISSUE THREAD

**Issue by eviltoylet** [bebraw/reactabular#25]
Since the API is getting close to final, I'll start adding in tests.

**Comment by bebraw** [comment]
Great. I merged the work to master and set up eslint. Feel free to do your work directly there. As long as eslint passes I'm fine.

**Comment by bebraw** [comment]
It's probably safe to close this one.

It would be a good idea to walk through the test coverage report generated to `build/` when testing and see if we can find aspects to test. There are likely zero cases and such that are missing.
