### ISSUE TITLE
Reactabular 0.5.0-beta2 is out

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#30]
You should be able to install it using `npm install reactabular@beta`. The current project README and demos are up to date. `gh-pages` hasn't been updated yet.

@eviltoylet, @spincycle please have a look if you have time.

**Comment by eviltoylet** [comment]
Great job! Looks pretty good to me :)

**Comment by bebraw** [comment]
@eviltoylet Any thoughts on #31?

**Comment by bebraw** [comment]
0.5.0 is out now!
