### ISSUE TITLE
Treat lodash as an extern instead?

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#31]
I noticed the lodash functions we depend upon bloat the dist version quite a bit (18k for minified). Would it make sense to convert lodash into a peer dependency and let Webpack depend on it as an extern (not included in the bundle)? Any thoughts?

I guess this would allow underscore to be plugged in provided the API and behavior is exactly the same and we're relying on functionality both provide.

**Comment by eviltoylet** [comment]
18K for minified?! Wow. I think it's definitely a smart move to declare lodash as an external dependency in Webpack. However, I'm not so sure about declaring it as a peer dependency.

**Comment by bebraw** [comment]
> However, I'm not so sure about declaring it as a peer dependency.

I guess we can drop even the peer dependency. We just need to document that the library requires lodash or underscore in order to work if we turn the dependencies into an extern. I'm not sure about compatibility with underscore so that's something I have to check out.

Anyway, thanks for your feedback. I think extern is the way to go.
