### ISSUE TITLE
Support grouped columns

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#33]
[Demo](https://facebook.github.io/fixed-data-table/example-column-groups.html).

I need to understand how to map this into a HTML `table` and Reactabular syntax.

**Comment by eviltoylet** [comment]
Let me know if you'd like some suggestions! As usual, I'm more than happy to provide them.

**Comment by bebraw** [comment]
Maybe it's better to start by figuring out data definition and API?

Here's what I expect data (individual entry) to look like for that Facebook demo:

```json
{
  "name": {
    "firstName": <str>,
    "lastName": <str>
  },
  ...
}
```

A column definition would look like this:

```javascript
var columns = [
  {
    "property": "name",
    "header": "Name"
    "children": {
      {
        "property": "firstName",
        "header": "First name"
        // customize cell here if you need
      },
      {
        "property": "lastName",
        "header": "Last name"
      }
    }
    // customizing cell here wouldn't do a thing because we are at parent
  },
  ...
];
```

Apart from that `children` entry the API would remain the same.

I'm still unsure what the generated HTML for this case should look like, though.

**Comment by eviltoylet** [comment]
Just some thoughts:
- Customizing a cell at a parent could be useful. For example, applying styling when both first name and last name are the same
- Might be able to do something like this: http://www.htmlhelp.com/reference/html40/tables/thead.html

**Comment by bebraw** [comment]
> Customizing a cell at a parent could be useful. For example, applying styling when both first name and last name are the same

Maybe that can be resolved with some sort of generic hook for customizing header rendering? I'm thinking something along:

```javascript
"header": (v) => <th>v</th>
```

So we just overload `header` like `cell` now to add more flexibility to the system without expanding the API.

> Might be able to do something like this: http://www.htmlhelp.com/reference/html40/tables/thead.html

That looks good. Thanks. I suppose the math could get interesting if we want to support recursion but even one level grouping could be enough for now.

**Comment by eviltoylet** [comment]
>Maybe that can be resolved with some sort of generic hook for customizing header rendering? I'm thinking something along:

>```javascript
>"header": (v) => <th>v</th>
>```

>So we just overload `header` like `cell` now to add more flexibility to the system without expanding the API.

I don't think we're on the same page here. This was your proposed column definition
>```javascript
>var columns = [
>  {
>    "property": "name",
>    "header": "Name"
>    "children": {
>      {
>        "property": "firstName",
>        "header": "First name"
>        // customize cell here if you need
>      },
>      {
>        "property": "lastName",
>        "header": "Last name"
>      }
>    }
>    // customizing cell here wouldn't do a thing because we are at parent
>  },
>  ...
>];
>```

I'm just suggesting that we shouldn't discount customizing a cell at that parent. At that parent level, we have information that each respective children doesn't have.

**Comment by bebraw** [comment]
> I'm just suggesting that we shouldn't discount customizing a cell at that parent. At that parent level, we have information that each respective children doesn't have.

Good point. I suppose on high level you might want to do something like:

```javascript
cell: (v, children) => {
    value: <span>...<children />...</span>
}
```

That would give you plenty of control.

Maybe doing that `header` thing I proposed might be a good idea anyway. We could push current `header.onClick` there etc. perhaps but this sounds like another issue.

**Comment by bebraw** [comment]
@eviltoylet Hey, do you want to revisit this? I might be able to squeeze in this feature at the next beta.

**Comment by bebraw** [comment]
Good example: https://www.w3.org/WAI/tutorials/tables/irregular/ .

Maybe `Table.Header` should accept a `header` definition of its own. The definition should be able to describe the nesting so it can be mapped to that example.

**Comment by bebraw** [comment]
There's a related proposal at #151.

**Comment by bebraw** [comment]
Implemented as `children` field.
