### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by MMore** [bebraw/reactabular#38]
Hi,

I tried the part "Searching a Table" from the readme file, but keep getting the following error:

    Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref

I see the table in the output. When I am changing the search text, I get further error messages like above. I am rendering the `TestTable` component (see code below).

```javascript
var Table = require('reactabular').Table;
var Search = require('reactabular').Search;

var TestTable = React.createClass({
  getInitialState: function() {
    var data = [
        {
            name: 'React.js',
            type: 'library',
            description: 'Awesome library for handling view.',
            followers: 23252,
            worksWithReactabular: true,
        },
        {
            name: 'Angular.js',
            type: 'framework',
            description: 'Swiss-knife of frameworks. Kitchen sink not included.',
            followers: 35159,
            worksWithReactabular: false,
        },
        {
            name: 'Aurelia',
            type: 'framework',
            description: 'Framework for the next generation.',
            followers: 229,
            worksWithReactabular: false,
        },
    ];
    var columns = [
        {
            property: 'name',
            header: 'Name',
        },
        {
            property: 'type',
            header: 'Type',
        },
        {
            property: 'description',
            header: 'Description',
        },
        {
            property: 'followers',
            header: 'Followers',
        },
        {
            property: 'worksWithReactabular',
            header: '1st Class Reactabular',
        },
    ];

    return {
      data: data,
      columns: columns,
      // Search `onChange` will emit a structure like this
      search: {
        query: '',
        column: ''
      }
    };
  },
  onSearch: function(search) {
    this.setState({
      search: search
    });
  },
  render: function() {
    var searchData = Search.search(
        this.state.search,
        this.state.columns,
        this.state.data
    );
    return (
      <div>
        <div className='search-container'>
            Search <Search columns={this.state.columns} onChange={this.onSearch} />
        </div>
        <Table columns={this.state.columns} data={searchData} />
      </div>
    );
  }
});
```

Do you have any idea what's wrong here?

**Comment by eviltoylet** [comment]
What version of reactabular are you using?

**Comment by MMore** [comment]
The current one v0.5.2.

**Comment by eviltoylet** [comment]
How are you rendering `TestTable` and anything that renders it? The entire ancestry tree rendering the `Search` component has to use `render()` because of our usage of `ref`s.

**Comment by eviltoylet** [comment]
@MMore are you still running into this issue? Please let us know so we can help you out more.

The use of `refs` will be removed for the next version, so this shouldn't be an issue in the near future.

**Comment by MMore** [comment]
I am using [react-rails](https://github.com/reactjs/react-rails#rendering--mounting). I will test it within the next days! Thanks for your help!

**Comment by MMore** [comment]
Now I have another error: `Uncaught TypeError: Search.search is not a function`. Maybe I understood the examples wrong, but in the readme in section **Searching a Table** a function `search` of the object `Search` is used. See my code above. Any idea?

**Comment by bebraw** [comment]
Great. Closing. Still a little bit of work before we can push `0.6.0` out.
