### ISSUE TITLE
Updates are delayed until the next render()

### ISSUE THREAD

**Issue by eviltoylet** [bebraw/reactabular#39]
The following changes aren't being reflected on the render correctly in the demo:
- inline/modal editor
- sorting when search term is present

**Comment by bebraw** [comment]
> sorting when search term is present

The problem is that sorted data and search data are two separate things in the demo. What if we treated sorting as a filter at `render()`? I think that would solve it. Now sort is imperative (triggered on click) which causes the problem.

**Comment by eviltoylet** [comment]
Yup, I'll allocate some time to fix this tonight.

**Comment by bebraw** [comment]
> Yup, I'll allocate some time to fix this tonight. On second look, it isn't as straight forward. The problem here is that the Search component takes care of the filtering on change to its input fields (the column selector and the query) but not to property changes.

One way is to deal with all the filtering at `render()`. `Search` would just expose some basic filtering mechanism you would hook into. At render you would execute a pipe like this: data -> search() -> sort() -> paginate(). That's probably not very performant but it would work for something simple like this and resolve our issue effectively.

This filtering logic can be easily pushed behind some Flux implementation. You would model all basic operations as actions and push the problem there. The benefit of this is that you can either use the filtering logic we provide or defer it to some backend. This layer can also contain caching. It is enough if we can provide hooks for users to achieve this.

**Comment by eviltoylet** [comment]
I do have a bandaid to make the demo work, but it definitely doesn't seem like best practice and isn't the most performant.

Having `Search` encapsulate the filtering doesn't quite work as mentioned above. I tried to fix this by using one of the component lifecycle methods (e.g. `componentWillReceiveProps(nextProps)`) to trigger the filtering. If I called the passed in `onChange` handlers, an infinite loop would ensue since the `onChange` sets state, and that in turn calls `render()` which then makes the `Search` component retrieve properties. `nextProps` and `this.props` pointed to the same object, so nothing really could be done to make sure that the props really did change.

There are probably a few places to break this loop, but I haven't given it much thought on the best place.

I ended up just invoking the `filterData()` method on `Search`. This is out as a pull request. If you have a better way, I definitely would like to see it.

**Comment by bebraw** [comment]
Would it help if pushed abstraction level up a notch? Now `sortColumn` and `search` return full data structures. What if instead they would provide something more meta? Ie. both would return lists of indices. You would then use this information at `render()` to construct an actual structure (ie. filter using search + sort based on sort indices). Do you think this would make sense?

This would be something between what I proposed and what you've been working on. Maybe that will break the infinite loop problem as well?

**Comment by eviltoylet** [comment]
Yeah, i think this is the right way to go. However, we should provide that pipeline as a core component. 

It seems really exciting! I can imagine having multiple search components piped together.

**Comment by bebraw** [comment]
Just realized there are two corner cases we need to worry about - adding and removing content. The index scheme can deal with latter easily. In the former case it gets more complicated. Maybe this just means search/sort logic needs to be triggered when you are modifying data.

> It seems really exciting! I can imagine having multiple search components piped together.

I hadn't thought of that. I suppose you could easily have a search field per header cell this way if you wanted.

**Comment by bebraw** [comment]
> Yeah, i think this is the right way to go. However, we should provide that pipeline as a core component.

I wonder what the API for that should look like exactly. We can have various components output indices and we can modify those on add/remove so the data stays consistent. The question is what the gluing part should look like. Maybe something like this?

```javascript
render() {
    var data = combine(this.state.data, this.props.search, this.props.sort, ...)

    // do pagination if you want (separate concern)
    ...
    // render now
    ...
}
```

`combine` would just do something like `data.filter((v) => indices.indexOf(v.id) >= 0)` per each.

**Comment by eviltoylet** [comment]
I don't see adding and removing content as that complicated as long as we always call `setState()` to force a render. The only thing I would change is not make `combine` take varargs, but rather an array. This solution may be overkill.

Honestly, this doesn't need to be solved now and may be out of scope for this library. This problem only exists because the demo has a lot of functionality.

**Comment by bebraw** [comment]
> I don't see adding and removing content as that complicated as long as we always call setState() to force a render. The only thing I would change is not make combine take varargs, but rather an array. This solution may be overkill.

Yeah, I can make the signature like `combine(this.state.data [...])`. Simpler API and a little easier to implement.

> Honestly, this doesn't need to be solved now and may be out of scope for this library. This problem only exists because the demo has a lot of functionality.

True. I have a feeling demo/docs need to be rethought at some point. Now it's getting a little unwieldy and doesn't illustrate possibilities in the best possible way.

I'll try doing a little branch with the fix in the coming week. Also need to investigate the edits. It's likely some id related thing (probably just in the demo but worth fixing anyway).

**Comment by bebraw** [comment]
Okay, this was one tiring week! I'll have another go at it next week. Sorry for the delay. A lot of things going on.

**Comment by bebraw** [comment]
@eviltoylet I set up a branch for this work. Now `Search` has been separated from filtering logic. Same goes for `sortColumn`. I split it up as well.

Unlike discussed above in both cases the logic takes in a structure and returns a new structure. The benefit of this is that you won't run into indexing problems (ie. if data has appearead, there's no need to update indices).

The split structure makes sense also when you are using Flux or have to work against a backend (just don't use our filtering logic in that case).

Please have a look and let me know if it looks ok to you and I'll wrap things up.

**Comment by eviltoylet** [comment]
:+1: I like this strategy. Originally I was hoping to encapsulate everything in the same component, but that seems to have caused more trouble than it was worth. I think if we really want that super easy to use component, we can just wrap these things as one.
