### ISSUE TITLE
Getting `Each child in an array should have a unique "key" prop.` for FullTable demo

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#45]
If I run the demo I get a warning. Looks like this is related to something in `FullTable` example. Note that if you remove the search control from `FullTable` no warning appears.

**Comment by eviltoylet** [comment]
This is coming from the highlighter formatter.

**Comment by bebraw** [comment]
Yeah, I guess those children might need unique keys. Just `highlight + i` or something.

Any particular reason why it's not in JSX?

**Comment by eviltoylet** [comment]
No particular reason. Just started as `React.createElement` and didn't realize it wasn't JSX.
