### ISSUE TITLE
Pagination broken after searching

### ISSUE THREAD

**Issue by ConAntonakos** [bebraw/reactabular#49]
Performing a search, then clicking on the paginated numbers, breaks the pagination whereby they are duplicated on either side of the ellipsis.

**Comment by bebraw** [comment]
@ConAntonakos Just to clarify, are you testing against NPM version or master?

**Comment by ConAntonakos** [comment]
Thanks for your reply, @bebraw. Sorry for the confusion. This is actually on the demo page.

**Comment by bebraw** [comment]
[The pagination widget](https://github.com/bebraw/react-pagify) did have some smaller issues which I've been patching since the online demo of Reactabular was released. I can see the issue you mentioned about there.

I suppose I'll leave this open till 0.6.0 is out and we'll have another look.

**Comment by bebraw** [comment]
It should work now. I fixed the issue at `react-pagify` and included that the current version of demo.
