### ISSUE TITLE
Republish on npm

### ISSUE THREAD

**Issue by djamshed** [bebraw/reactabular#51]
Coming across some of the closed issues when using rectabular thru npm (same version, but more than a month behind the latest).

**Comment by bebraw** [comment]
A release is close. #39 seems to be the biggest blocker.

Thanks for the heads up!

**Comment by bebraw** [comment]
@djamshed I published `0.6.0` beta. If you want to have a look, please try `npm i reactabular@beta`. The current README is based on that version although we intend to change this from now on (separate dev branch).

**Comment by bebraw** [comment]
`0.6.0` is up now.

**Comment by djamshed** [comment]
Great, thanks!
