### ISSUE TITLE
Custom Search Component

### ISSUE THREAD

**Issue by daannijkamp** [bebraw/reactabular#54]
For a project I want to use the search component. Only I need to remove some parts like the select and the surrounding <span> element
```
        return (
            <span className='search'>
                <select onChange={this.onColumnChange} value={this.state.column}>{options.map((option) =>
                    <option key={option.value + '-option'} value={option.value}>{option.name}</option>
                )
                }</select>
                <input onChange={this.onQueryChange} value={this.state.query}></input>
            </span>
        );
```

```
        return (
            <input onChange={this.onQueryChange} value={this.state.query}></input>
        );
    },
```

How can I achieve that?
If I copy reactabular src in my project and do my change, I will get this error:
```
Uncaught TypeError: Search.search is not a function
```
What am I doing wrong?
```
  render() {
    var searchData = Search.search(
      this.state.search,
      this.state.columns,
      this.state.data
    );
    return (
    <div>
      <NavigationBar>
          <Search columns={this.state.columns} onChange={this.setState.bind(this)}></Search>
        </NavigationBar>
      <Table className="tables" columns={columns} data={searchData} />
    </div>
  );
}
```

**Comment by bebraw** [comment]
You have to import `Search` from reactabular for `Search.search` to work. Ie. something like this:

```javascript
var Search = require('./YourSearch');
var search = require('reactabular).Search.search; // dig the search function you need

...
var searchData = search(this.state.search, ...);
```

I hope that helps.

**Comment by daannijkamp** [comment]
:cry:  
After a put something in the input field. The data state will be empty.
![screenshot from 2015-05-29 11 24 47](https://cloud.githubusercontent.com/assets/1774060/7879954/6265d26a-05f5-11e5-919b-551c8cc58bc8.png)
(Search State, Column State, Data state)

**Comment by bebraw** [comment]
@daannijkamp Can you set up a little repo for me to study?

The API will likely change soon but it still would be nice to get it work for you.

**Comment by daannijkamp** [comment]
Thanks!
https://github.com/daannijkamp/reactabular-test/

**Comment by bebraw** [comment]
@daannijkamp Try this:

```javascript
  render: function() {
    var searchData = search(
      this.state.search,
      this.state.columns,
      this.state.data
    );
    return (
      <div>
        <NavigationBar>
          <SearchBar columns={columns} onChange={this.updateSearch}></SearchBar>
        </NavigationBar>
        <Table columns={columns} data={searchData} />
      </div>
    );
  },
  updateSearch: function(search) {
    this.setState({
      search: search,
    });
  },
```

The problem was that it wasn't dealing with the search state correctly. That's why `search` didn't filter using the correct values.

Feel free to close if this works for you.

**Comment by daannijkamp** [comment]
-_- 
Cannot read property 'setState' of undefined

**Comment by bebraw** [comment]
@daannijkamp https://github.com/bebraw/reactabular-test . There's the fix that worked for me. Maybe there was a typo or something?

**Comment by daannijkamp** [comment]
Found it... it was because i'm using ES6.  @bebraw thank you very much for all your help!

**Comment by bebraw** [comment]
@daannijkamp Great to hear you solved it! Btw please check out my Webpack/React book for some inspiration, http://survivejs.com/.
