### ISSUE TITLE
Reactabular is slooooooow

### ISSUE THREAD

**Issue by invoke-git** [bebraw/reactabular#58]
We've detected a massive performance problem with reactabular.  We have a table with 600 rows of 6 columns: a link column, a text column, 2 datetime columns (displayed as text) , and a column with a trash can icon.  We observed times of up to 3.8 seconds to render this table.  We did a test and replaced reactabular with simple div-based rendering and it rendered in 300ms.  We're using react isomorphically so we're observing that this slow time is due our node server chewing up the CPU.

We haven't identified the problem within reactabular that's causing the slowness yet.

**Comment by bebraw** [comment]
Thanks for letting me know! I'm using it with pagination while showing only a small amount of data. The library hasn't been optimized when it comes to performance. It was more about providing a flexible API. As far as I understand Facebook's [FixedDataTable](https://facebook.github.io/fixed-data-table/) has focus on performance.

That said if we can find some ways to make Reactabular perform faster I'm in. The first step would be identifying what causes the slowness. Next we can try to do something about it.

**Comment by invoke-git** [comment]
Yeah we'll be implementing pagination on this table so it will be less visible in the future.  Right now we're pre-release so we're not going to make any changes or investigate at the moment but as we get closer to it mattering we'll look into it further.

**Comment by utdemir** [comment]
Just for information: We're using reactabular 0.6.3 showing about 900x2 table on client side without pagination(but using onClick handles, styles, search etc.), it loads instantly.

So, maybe the problem is in server-side rendering or column count.

**Comment by bebraw** [comment]
@invoke-git Any chance you could set up a little example for me to study? I would love to understand what's making it slow in your case.

**Comment by bebraw** [comment]
@invoke-git I think we finally got it! Now you can set `rowKey={'id'}`. That will allow React to benefit from proper diffing. Just set that to id of your row items and that should help considerably. Let me know how it goes.

**Comment by invoke-git** [comment]
We've paginated everything that used to display the slow behavior so we'll have to cook up a test.  I'll give it a shot and let you know how it goes.
