### ISSUE TITLE
Recommended way to construct cell function for nested json object?

### ISSUE THREAD

**Issue by cameront** [bebraw/reactabular#60]
Thanks for the awesome library! I'm just trying to incorporate reactabular into a project today, and I've run into a bit of an issue.

I have a json object that comes back from some remote API which contains nested objects. I was expecting that I could just use the 'cell' function to render a complex object (e.g. a nicely named link), but I've become confused about the way that reactabular renders columns.

Imagine a simple nested data structure describing people (and de-normalized nested structures describing their fathers). E.g:
```js
var people = [
  { id:100, name:"Adam", dad:{id:20, name:"John"} },
  { id:101, name:"Brian", dad:{id:22, name:"George"} }
];
```

I assumed I could use a cell function in my columns definition like this:
```js
var columns = [
  {
    property: 'name', 
    header: 'Name'
  },
  {
    property: 'dad',
    header: 'Dad',
    cell: function(v) { return <a href={'/people/' + v.id}>{v.name}</a>; }
  }
];
```

But it doesn't work like that... and I'm not entirely sure why. The block that has me confused is https://github.com/bebraw/reactabular/blob/master/src/table.js#L84. It seems strange that if v is an object, my cell function is called but with the `v.value` field instead of the value itself, and that is merged with the existing value.

So I thought this code must exist for some specific case that just happens to be colliding with mine -- and thought I'd ask about it before going to the trouble of submitting a PR. It looks like it might have been added in response to trying to detect react elements (https://github.com/bebraw/reactabular/commit/11cc4a416d3f4d2571d775f4f73adfeca77a16ba#commitcomment-10338596), but the more I look at that map function, the more confused I get, so perhaps some comments (which I'd be happy to add once I understand) would help people trying to use that api.

So, I have 2 questions:

1. Is there a recommended way of doing what I'm trying to do that I'm not realizing?
2. Would you be open to a PR that either:
  * documents current choices
  * simplifies the cell api a little bit?

**Comment by cameront** [comment]
OF COURSE I have an epiphany 30 seconds after hitting send.

So I'm assuming that the isPlainObject() case is trying to account for objects returned with properties that should be passed along to the rendered table cell? In that case, it's still not clear to me why the cell function is called on those values as the object is merged.

What I'll do is just mail a PR that explains my thinking -- and you can let me know if I'm breaking use-cases you'd like to support.

**Comment by bebraw** [comment]
@cameront Yeah, I never really thought about nested cases like that and it's quite possible there's some stupid check against that. I agree

```javascript
cell: function(v) { return <a href={'/people/' + v.id}>{v.name}</a>; }
```

would seem natural approach to me and it would be nice if that worked.

PR is welcome! Note that Jest won't work with Node 0.12 though 0.10 is known to work.
