### ISSUE TITLE
Implement a proper documentation site

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#69]
I feel the current README is getting unwieldy. If it was possible to keep that simple enough perhaps we could drop `dev` branch and go back to working against `master`. That's a little confusing to potential authors as most of the other projects work against `master`.

Most likely I'll need to extend [Antwar](https://antwarjs.github.io/) to support this scenario well enough. Now it's a little lacking when it comes to actual JavaScript support.

**Comment by bebraw** [comment]
I split it up at `docs`. It should be much easier to set up a proper site now.

**Comment by tBaxter** [comment]
add a README.md to docs/ with links to the individual files in there and a description of what you'll find in each. Boom: instant github doc site.

**Comment by bebraw** [comment]
@tBaxter Yeah. That's a cool idea and would work for now. 👍 

I am actually working on a heavier duty alternative but it will take a while to complete on a sufficient level. What you suggest would work well till the tool is where it needs to be.
