### ISSUE TITLE
Use tab key to navigate editable table?

### ISSUE THREAD

**Issue by emma58** [bebraw/reactabular#72]
In an editable table, is there an easy way to change the focus to the next cell in the table using the tab key?

**Comment by bebraw** [comment]
Good question. I expect you would have to use something to track `tab`. [react-hotkeys](https://github.com/Chrisui/react-hotkeys) could work for instance.

After you know how to track tab, you'll need to set `editProperty` of [edit.js](https://github.com/bebraw/reactabular/blob/12fc2ef47838c4a14216a39e7f9e20b7fdafef7b/src/cells/edit.js) to point at the cell you want to edit.

You can see a rough example of how to deal with edit at [full_table.jsx](https://github.com/bebraw/reactabular/blob/81aa82323061c0f3ba6f5e9f7ca8c1fb79f5e7d4/demos/full_table.jsx#L55). You'll need to add that tabbing logic there, though. It might be possible to get away without `react-hotkeys` but you would have to try to know for sure.

Let me know if you run by any issues. I can give this a go later as it's an interesting problem.

**Comment by bebraw** [comment]
There's a [selection example](https://bebraw.github.io/reactabular/#/examples/selection) now. I'm thinking a similar idea would work for tabbing. There's also enough control over edited cell now so that you can move it around as a cursor.

Note that this is available only in the current beta.
