### ISSUE TITLE
Make sure editor state updates while filtering at demo

### ISSUE THREAD

**Issue by bebraw** [bebraw/reactabular#73]
To quote @cresh:

> Currently, this functionality seems to be missing. This is also reproducible with the demonstration table at https://bebraw.github.io/reactabular/ : Click on the name in the first row to start editing the name. Then click into the search box and search for another name in the table. Note that the contents of the input editor does not change with the rest of the row. The rest of the row correctly shows data that belongs to the name you've searched for.

**Comment by eviltoylet** [comment]
I'm not seeing this behavior right now. Did it get inadvertently fixed?

**Comment by bebraw** [comment]
Yeah, I made it to cancel edit on search so that accidentally fixed this behavior. I felt it doesn't make sense to have editors open while searching. Closing.
