### ISSUE TITLE
How to Implement React Tabular

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#75]
Hi @bebraw How can I implement ReactTabular in tomcat server .

And how can I achieve React-Tabular features in my tomcat project. I am using react-bootstrap with bower-component.
Could you plz suggest

**Comment by bebraw** [comment]
Hi,

I don't have any server specific advice to give. It is likely the best if you can consume it through npm.

Do you have some particular problems with it?

**Comment by ranjan653** [comment]
Hi I can download code from Github but how to implement in my project.

**Comment by ranjan653** [comment]
Could you please provide one example in single page with library so that I
will be grateful to u.

**Comment by bebraw** [comment]
Hi,

The [demos](https://github.com/bebraw/reactabular/tree/master/demos) and the [README](https://github.com/bebraw/reactabular/blob/master/README.md) might be your best bets. Once you understand how various parts work together, it gets easier to use. It's one of those libraries you have to spend some time assembling to fit your purposes. :+1:

**Comment by ranjan653** [comment]
Hi that I have read but how to achieve

var Search = require('reactabular').Search;

I have problem with require.

Please help me, otherwise my job will be in trouble.. I have to
implement reactabular.

**Comment by bebraw** [comment]
> I have problem with require.

What kind of problem? Can you provide more context or an error? If you can, please set up a little example on GitHub for me to study.

**Comment by ranjan653** [comment]
Hi Please find it.

"ReferenceError: require is not defined".

I have download the code from Git:-https://github.com/bebraw/reactabular

But in single page how to implement it.


Like below

<script src="DatePicker/datepicker-ui.js"></script>
<script src="bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet"
href="bootstrap-datepicker/css/bootstrap-datepicker3.css">
<script src="js/bootstrap.js"></script>
<script src="js/bower_components/react/react-with-addons.js"></script>
<script src="js/bower_components/react/JSXTransformer.js"></script>
<script src="js/bower_components/react-bootstrap/react-bootstrap.min.js"></script>
<script type="text/jsx" src="components/data.js"> </script>
<link rel="stylesheet" href="css/screen.css">
<script src="js/lodash.min.js"></script>
<script src="js/bower_components/reflux/dist/reflux.js"></script>

I can access the method or .....present in library. so please how can
i achieve that

**Comment by ranjan653** [comment]
Hi, which library will implement so that require will be available and
easily achieve

like

var Search = require('reactabular').Search;

**Comment by bebraw** [comment]
Ah, I see the problem now.

```javascript
var Search = require('reactabular').Search;
```

assumes that you operate within a Webpack environment. Similar would work for Browserify as well.

It might work better for you to work against the [dist](https://github.com/bebraw/reactabular/tree/master/dist) version. Then you can do something like this:

```html
<script src="js/reactabular.min.js"></script>
```

```js
var Search = Reactabular.Search;
```

This assumes you copy `reactabular/dist/reactabular.min.js` below your `js` directory. As you can see, using this approach it will inject itself as a global as per UMD wrapper. This version also works in AMD/CommonJS environments if needed.

**Comment by ranjan653** [comment]
Hi @bebraw , Thanks a lot for your help.

I am able to implement 
var Search = Reactabular.Search;
var Table = Reactabular.Table;
but how to Implement 
var highlight = require('reactabular/formatters/highlight');

I have highlight.js file in formatters what should write instead of  require('reactabular/formatters/highlight')

**Comment by bebraw** [comment]
1. I provide some very [basic styling](https://github.com/bebraw/reactabular/blob/master/style.css) you can copy. Ideally you'll write something to suit your purposes. You can also attach custom classes to the elements as you need.
2. I think `var highlight = Reactabular.formatters.highlight` should work. Note that you can inspect the object in browser through `console.log(Reactabular)` to figure out how it has been laid out.
3. Get the [dist version](https://github.com/bebraw/react-pagify/blob/master/dist/react-pagify.js). After that it's the same ideas as for Reactabular except in this case you can access the paginator object through `ReactPagify` global.

**Comment by ranjan653** [comment]
Thanks.

You have mention 
data = sortColumn.sort(data, this.state.sortingColumn);
What sortingColumn includes.

could you please provide a simple example contains
Table contains paging inline editing, row edit, search,sorting

Your actual example contains less items, to make understand difficult. Plz.........

**Comment by bebraw** [comment]
There are two parts to that. I.e. in demo I do:

```javascript
header: {
    onClick: (column) => {
        // reset edits
        this.setState({
            editedCell: null
        });

        sortColumn(
            this.state.columns,
            column,
            this.setState.bind(this)
        );
    },
},
```

If you look at [the code](https://github.com/bebraw/reactabular/blob/master/src/sort_column.js), you can see it resets class state and adjusts the state of the selection. That's why we do `setState` finally.

`sortColumn.sort` operates based on this during rendering to actually filter the data. This gives that `data = sortColumn.sort(data, this.state.sortingColumn)` in the demo.

You'll need these both parts for it to work.

I agree the demo/docs could be better but this is a casual project for me so I work only when I have some spare time. :+1:

**Comment by ranjan653** [comment]
Could you please prepare one example having paging inline editing, row edit, search,sorting, remove row for me , when you are free.

Its very important for me.

**Comment by bebraw** [comment]
Hi,

[The full table](https://github.com/bebraw/reactabular/blob/master/demos/full_table.jsx) demo is probably the closest I can get on a volunteer basis. It has all the basic bits.

The way you implement Reactabular in your project depends on architecture (Flux, whatnot) so it's hard to give a single example that would work for each possible case. It's important to understand how the individual parts work and how to fit them together. After that you can adapt.

**Comment by ranjan653** [comment]
Hi I have that file full_table.jsx. How i can achieve in my jsx
var FullTable = require('./full_table.jsx');

It contains so many require command how can i avoid it.


var Form = require('plexus-form');
var validate = require('plexus-validate');
var SkyLight = require('babel!react-skylight/src/skylight.jsx'); // XXX: no proper build yet
var generators = require('annogenerate');
var math = require('annomath');
var Paginator = require('react-pagify');
var titleCase = require('title-case');
var findIndex = require('lodash/array/findIndex');

var Table = require('../src/table');
var Search = require('../src/search');
var editors = require('../src/editors');
var sortColumn = require('../src/sort_column');
var cells = require('../src/cells');

var FieldWrapper = require('./field_wrapper.jsx');
var SectionWrapper = require('./section_wrapper.jsx');
var countries = require('./countries');
var generateData = require('./generate_data');

var highlight = require('../src/formatters/highlight');

**Comment by bebraw** [comment]
You can access all parts of the library through `Reactabular` global in your case. So instead of doing something like `var editors = require('../src/editors');`, you would go through the global instead. The global contains an object that maps to the functionality. You can try inspecting it through Chrome Inspector or a similar tool to understand how it has been laid out.

**Comment by ranjan653** [comment]
What I am trying to say I made a JSX file 
I want to include this 
var FullTable = require('./full_table.jsx');

What should write here instead of require('./full_table.jsx');

**Comment by bebraw** [comment]
> What should write here instead of require('./full_table.jsx');

It might be beneficial to pick up a module bundler to deal with all that. I go through a nice [Webpack](https://webpack.github.io/) based setup at [my book](http://survivejs.com/webpack_react/introduction/). Alternatively you could look into [Browserify](http://browserify.org/) or [jspm](http://jspm.io/).

I know picking one up will take some time. That will allow you to use `require` etc. and end up with a bundle that's easy to serve. Over longer term it's a nice idea to learn to use one.

**Comment by ranjan653** [comment]
Hi For ReactPagify I am include react-pagify.js

<script src="js/react-pagify.js"></script>	
but when I am declaring Paginator like below 
 var Paginator =ReactPagify.Paginator;

in console.log(Paginator ) showing undefined

**Comment by bebraw** [comment]
Note that `ReactPagify` is the component itself. So you get

```javascript
var Paginator = ReactPagify;
var paginate = Paginator.paginate;
```

and so on.

Again, printing through the console helps to understand how it's structured better. You can also try importing the modules through Node cli as that gives the same result.

**Comment by ranjan653** [comment]
Can I talk over phone ?

**Comment by bebraw** [comment]
@ranjan653 [gitter](https://gitter.im/bebraw/reactabular) would work. Phone is expensive. :)

**Comment by ranjan653** [comment]
Its fine for me can we..

**Comment by ranjan653** [comment]
Hi I am on the way  to implement your ReactTabular full_table.jsx

Can you provide some information to implement below things with library. I have 
field_wrapper.jsx,section_wrapper.jsx,generate_data.js  and I have added like 
<script src="js/reactabular.min.js"></script>

How to add for below things

var Form = require('plexus-form');
var validate = require('plexus-validate');
var SkyLight = require('babel!react-skylight/src/skylight.jsx'); // XXX: no proper build yet
var generators = require('annogenerate');
var math = require('annomath');
var titleCase = require('title-case');
var findIndex = require('lodash/array/findIndex');
var FieldWrapper = require('./field_wrapper.jsx');
var SectionWrapper = require('./section_wrapper.jsx');
var countries = require('./countries');
var generateData = require('./generate_data');


Could you provide information

**Comment by ranjan653** [comment]
Kindly go through my error


![error-reactabular](https://cloud.githubusercontent.com/assets/6347884/9786626/1bbd2c56-57d9-11e5-9c32-738566fe0124.png)

**Comment by bebraw** [comment]
Is it possible for you to put a standalone project somewhere to study?

The demo relies on Webpack and you can get similar results with a bundler such as Browserify. These tools will evaluate `require` graphs and provide you a simple bundle you can link to. That's the way the demo works. Please see the free guide I linked to. It goes into great detail in how to achieve this. I've put a lot of time and effort to that and I hope you find it useful.

**Comment by ranjan653** [comment]
Yes @beraw I will provide my code to review. But I am going through the docs but to complete your full table I need little help by providing some information regarding how to implement and the library.

var Form = require('plexus-form');
var validate = require('plexus-validate');
var SkyLight = require('babel!react-skylight/src/skylight.jsx'); // XXX: no proper build yet
var generators = require('annogenerate');
var math = require('annomath');
var titleCase = require('title-case');
var findIndex = require('lodash/array/findIndex');
var FieldWrapper = require('./field_wrapper.jsx');
var SectionWrapper = require('./section_wrapper.jsx');
var generateData = require('./generate_data');

Will you do it for me..?

**Comment by bebraw** [comment]
Getting all that work without some kind of a bundler would be pretty time consuming. It's likely better to pick up one as that will solve a lot of your problems.

**Comment by ranjan653** [comment]
I can't get you

**Comment by bebraw** [comment]
I mean converting all that to a big list of `<script src="js/findIndex.js"></script>` references wouldn't be practical. You would have to look up each dependency and maintain it all by hand. npm and a bundler (webpack/browserify/jspm) can deal with all that for you. Did you check the book?

**Comment by ranjan653** [comment]
Hi Juho, I cannot access below site provided by you as well as gitter

http://survivejs.com/webpack_react/introduction/

**Comment by ranjan653** [comment]
Hi, I just go through the docs but could not find any solution that how to implement
I have generate_data.js file, but when I implemented its throwing error. As it is not finding.

var generators = require('annogenerate');
var math = require('annomath');
var properties2object = require('schema2object').properties2object;

COuld you please guide.

**Comment by bebraw** [comment]
Hi,

That

```javascript
var generators = require('annogenerate');
var math = require('annomath');
var properties2object = require('schema2object').properties2object;
```

part is related only the demo. You don't need to implement that. Instead, you'll pass your own data to it.

**Comment by ranjan653** [comment]
Hi,
You are right. But which library file to include,  like 
<script src="js/reactabular.min.js"></script>
so that I can achieve 
var generators = require('annogenerate');
var math = require('annomath');
var properties2object = require('schema2object')

**Comment by bebraw** [comment]
@ranjan653 Can you set up an example repo and add instructions there to show what you need to achieve? I need to understand what sort of data you are going to show and how.

**Comment by ranjan653** [comment]
Ok, I will create a repo and upload my code there. I just want to implement your given table with all functionalities with same data. i.e data Name,Position,Country,Salary.If I will able to finish this task then will try for other.

**Comment by ranjan653** [comment]
Hi ,
Could you please go through the code that I have check-in to git

https://github.com/ranjan653/Reactabular_Ranjan/blob/master/Reactabular.html


Thanks
Ranjan

**Comment by bebraw** [comment]
The main problem is that you simply cannot use `require` like that within a `script` tag. As I explained many times already, you will likely want to use a bundler to deal with all the complexity.

I've spent enough of my time on this. Can we move this to my consulting side? I can give you a fair rate.

**Comment by ranjan653** [comment]
Could you please let me know about the rate and how can you help me.
Is it possible to solve this problem by coding like this ?

**Comment by bebraw** [comment]
@ranjan653 Can you send an email (bebraw at gmail dot com) with a basic specification of what you need exactly? The more specific you can be, the better. I'll make an offer based on that.

Note that there are more popular alternatives like [FixedDataTable](https://facebook.github.io/fixed-data-table/) and [reactable](https://github.com/glittershark/reactable). These may be easier to approach than reactabular. The design is more flexible but as a result it's harder to use. :)

**Comment by ranjan653** [comment]
That's right but thing is that I need below feature.

1/ individual column sorting
2/ individual column searching
3/ each column data can edit including date picker field
4/ each row can edit with popup
5/ each row can delete
6/ paging facility
7/ scrolling
8/ Onclick ?(add row) popup  data can add to table
