### ISSUE TITLE
Feature Request: Column header function handler

### ISSUE THREAD

**Issue by reggi** [bebraw/reactabular#76]
I'm looking for a way to add a class to a column, is this possible?

```js
var columns = [
  {
    property: 'order',
    header: 'Order',
    props: {
      className: 'selected'
    }
  }
]
```

**Comment by reggi** [comment]
I'm trying to mimic the functionality below, one heading is an element, and the other has a carrot (added by class). 

![screen shot 2015-09-16 at 5 07 28 am](https://cloud.githubusercontent.com/assets/296798/9900817/5663d5ce-5c31-11e5-855c-aba855171a9d.png)


Ideally `header` could be a function handler like cell and I can return a JSX element from there.

```
header: function () {
  return 'Anything'
}
```

**Comment by bebraw** [comment]
I think #65 should allow the customization you need. Gotta poke that.

**Comment by bebraw** [comment]
@reggi It's possible to inject custom headers now. Please have a look at the current version.

**Comment by Ezekiah** [comment]
Hello I tried to use this enhancement but it doesn't work it displays nothing:

 columns: [

				{
				  property: 'selected',
				  header: function() {
					  return (<input type="checkbox"  selected={false} />)
				  },


Could you help me ?

**Comment by bebraw** [comment]
@Ezekiah See https://github.com/bebraw/reactabular/blob/master/docs/customizing_header.md . Maybe `columnNames` is the key. If you can upload your project to GitHub, I can have a closer look.

**Comment by Ezekiah** [comment]
Yeah columnNames is used in full_table.js.
Here is my version of full_table. https://gist.github.com/Ezekiah/c8294613aef0f9f4c8d0
I added  "selected" cell to implement the multiselect feature, but I dunno how I can add an input in the header

**Comment by bebraw** [comment]
@Ezekiah Ah, it was simpler than I remembered. Try something along `header: <input type="checkbox" selected={false} />`. No need to wrap in function. It expects a React element. Incidentally text happens to work by default. See `src/column_names.js` for exact details.

**Comment by bebraw** [comment]
I'm closing this issue given header is somewhat customizable now and it should be possible to achieve what was originally requested.
