### ISSUE TITLE
How to hide a column in Reactabular?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#77]
I have data and column like below. I want to hide one column i.e.followers

var data= [
    {
        name: 'React.js',
        type: 'library',
        description: 'Awesome library for handling view.',
        followers: 23252,
        worksWithReactabular: true,
    },
    {
        name: 'Angular.js',
        type: 'framework',
        description: 'Swiss-knife of frameworks. Kitchen sink not included.',
        followers: 35159,
        worksWithReactabular: true,
    }]
	
	var columns = [
    {
        property: 'name',
        header: 'Name',
		cell: [editable({
              editor: editors.input(),
           })],
   
		
    },
    {
        property: 'type',
        header: 'Type',
		cell: [editable({editor: editors.input(),})],
		
    },
    {
        property: 'description',
        header: 'Description',
		cell: [editable({
              editor: editors.input(),
           })],
		
    },
    {
        property: 'followers',
        header: 'Followers',
		
		search: (followers) => followers - (followers % 100),
		cell: [editable({
              editor: editors.input(),
           })],
		
    },
	
	 <Table columns={columns} data={data} />

**Comment by bebraw** [comment]
The simplest way to achieve that is simply to remove the column you don't need to show from your column definition. You probably need some other logic to control this if you need to show the column again. That's something you can solve on React's side. `Table` just shows what you pass to it.

**Comment by ranjan653** [comment]
Hi, @bebraw ,that's one point of view. But I have one ID, through which I can edit and delete the row i.e back-end operation.

**Comment by bebraw** [comment]
I think you'll still have access to the id even if you don't show the id column at all. If I understand right, just removing the id from column definition should do the trick.

**Comment by ranjan653** [comment]
That ID is unique, If I remove the id from column definition, how would i get the id to delete or edit the row ( you mean row index), but through row index i cannot go for backend-operation

**Comment by bebraw** [comment]
I think you may need to do it in two parts: 1. seek the row data based on row index 2. get `id` property from there.

I agree it might not be an ideal interface. It could be better to pass whole row data to `editable` to make these kind of things easier.

**Comment by ranjan653** [comment]
Yes Sir,
My table is dynamic (may be 20 columns come after web service call or 30 columns). That's the problem.How can I hide the column a big problem.

can I add ClassName  in this

         {
                    property: 'name',
                    header: 'Name',
                                    },
So that the column will be hide

**Comment by bebraw** [comment]
If you look at `src/table.js`, you can see a line like

```js
className={cx(column.classes)}
```

This means you can do for example

```javascript
{
  property: 'name',
  header: 'Name',
  classes: {hidden: true}
},
```

See [classnames](https://www.npmjs.com/package/classnames) for details. I need to document this as it wasn't on readme.

**Comment by ranjan653** [comment]
Yes Sir,
I found that's working fine.

see image data hide successfully but column does not hide
![chart-image](https://cloud.githubusercontent.com/assets/6347884/9907074/0a045814-5cab-11e5-807b-072ab2677169.png)
 var data= [
    {
        name: 'React.js',
        type: 'library',
        description: 'Awesome library for handling view.',
        followers: 23252,
       
    },
    {
        name: 'Angular.js',
        type: 'framework',
        description: 'Swiss-knife of frameworks. Kitchen sink not included.',
        followers: 35159,
       
    },
    {
        name: 'Aurelia',
        type: 'frameworkRanjan',
        description: 'Framework for the next generation.',
        followers: 229,
       
    },
];

What should write in data....or what should mention?

**Comment by bebraw** [comment]
Ah, forgot about that. Of course it doesn't hide the column given the table layout works...

As I mentioned earlier, you will make your life far simpler by removing the column you want to hide from the column definition. You can still dig the data you need when you need it. The data definition can contain all fields you like. Reactabular doesn't care about that.

I hope that's it.

**Comment by ranjan653** [comment]
Ok, I will hide the column and by index I can get the particular id from that like

this.state.data[rowIndex].id
I have to declare two variable 
is it ok ?

**Comment by bebraw** [comment]
> this.state.data[rowIndex].id
> I have to declare two variable 
> is it ok ?

Sure.

**Comment by ranjan653** [comment]
Hi, I just keep all data and remove that column name from columns. It hide the column. 
Thanks @bebraw

**Comment by bebraw** [comment]
Great.
