### ISSUE TITLE
Is it possible for horizontal and vertical scroll in Reactabular ?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#80]
Is it possible for horizontal and vertical scroll in Reactabular ?

**Comment by bebraw** [comment]
Can you expand? I can see multiple ways to achieve that.

You can for instance use CSS and overflow with `tbody`.

**Comment by ranjan653** [comment]
MY code is

return (
		
            <div>
			    <div className='controls'>
                    <div className='per-page-container'>
                        Per page <input type='text' ></input>
                    </div>
                    <div className='search-container'>
                        Search <Search columns={columns} data={this.state.data} onChange={this.onSearch} />
                    </div>
                </div>
            <Table2 columns={columns} data={data} row={(d, rowIndex) => {
                        return {
                            className: rowIndex % 2 ? 'odd-row' : 'even-row',
                            onClick: () => console.log('clicked row', d)
                        };
                    }} className="pure-table pure-table-striped"/>
			
			
               </div>
        );
    },

**Comment by bebraw** [comment]
See #50.

That should be related to your issue. There's one potential solution. Sticky headers would take more work and I don't have time for that at the moment.

**Comment by ranjan653** [comment]
ok..

**Comment by ranjan653** [comment]
ok

**Comment by ranjan653** [comment]
I think main.css ,style.css are the css you have used in reactabular. If you have used other than this css. could you plz provide.

**Comment by bebraw** [comment]
You most likely have to write the CSS you need by hand. I don't have anything specific for this use case apart from the solution I linked to at #50.

**Comment by ranjan653** [comment]
I am looking to this issue
