### ISSUE TITLE
Sorting not working in Reactabular, header click ?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#82]
Hi, When click on reactabular header, data fetching, but sorting not working. Showing below error

**Comment by bebraw** [comment]
That means your `columns` definition is not an array. You could try some standard debugging techniques at your click handler.

**Comment by ranjan653** [comment]
OK Sir, 

Could you plz look into the code.Any thing need to change

var From = React.createClass({
getInitialState: function() {

    return {
	search: {
            column: '',
            query: ''
        },
		header: {
                onClick: (column) => {
                    
					
                    this.setState({
                        editedCell: null
                    });
                    sortColumn(
					
                        this.state.columns,
                        column,
                        this.setState.bind(this)
                    );
					console.log(this.state.columns);
					console.log(column);
                },
            },
      data: data123,
      };
  },

  


onSearch(search) {
    this.setState({
        search: search
    });
},

render: function() {
 
var data = this.state.data;

var header = this.state.header;

var pagination = this.state.pagination;
//var paginated = Paginator.paginate(data, pagination);


var editable = cells.edit.bind(this, 'editedCell', (value, celldata, rowIndex, property) => {
    var idx = _.findIndex(this.state.data, {
        id: celldata[rowIndex].id,
    });
	
    this.state.data[rowIndex][property] = value;
alert("hiii I am in Cell Edit");
    this.setState({
        data: data,
    });
});

var highlighter = (column) => highlight((value) => {
//console.log(Search.matches(column, value, this.state.search.query));
    return Search.matches(column, value, this.state.search.query);
});
var columns = [
    {
        property: 'EFF_DT',
        header: 'EFF_DT',
		cell: [editable({
              editor: editors.input(),
           }),highlighter('EFF_DT')],
   
		    },
    {
        property: 'ARP_CD',
        header: 'ARP_CD',
		cell: [editable({
              editor: editors.input(),
           })],
		    },

    
];

    if (this.state.search.query) {
            data = Search.search(
            data,
            columns,
            this.state.search.column,
            this.state.search.query
        );
    }
	sortingColumn: null,
	data = sortColumn.sort(data, this.state.sortingColumn);
	
        return (
		
            <div >
			    <div className='controls'>
                    <div className='per-page-container'>
                        Per page <input type='text' ></input>
                    </div>
                    <div className='search-container'>
                        Search <Search columns={columns} data={this.state.data} onChange={this.onSearch} />
                    </div>
                </div>
            <Table2 header={header} columns={columns} data={data} row={(d, rowIndex) => {
                        return {
                            className: rowIndex % 2 ? 'odd-row' : 'even-row',
                            onClick: () => console.log('clicked row', d)
                        };
                    }} className="pure-table"/>
			
			
               </div>
        );
    },

	
});

**Comment by ranjan653** [comment]
Hello Sir, My column list is coming like 

![columns list](https://cloud.githubusercontent.com/assets/6347884/9953515/129f4c22-5dff-11e5-91c6-b76e3fce6a17.png)

**Comment by bebraw** [comment]
It's very hard for me to debug this way.

It may be a good idea to push sorting to backend level. In that case you would just update the data based on a query you send on click. Unless you have all the data available at frontend, this is the only reliable way I can see.

**Comment by ranjan653** [comment]
Actually sir, whatever you have written I am just following your code. May be I am wrong somewhere. I just squeezed my code . Could you plz look into it


var From = React.createClass({
getInitialState: function() {

    return {
	search: {
            column: '',
            query: ''
        },
		header: {
                onClick: (column) => {
          	        sortColumn(
					    this.state.columns,
                        column,
                        this.setState.bind(this)
                    );
					
                },
            },
      data: data123,
      };
  },

render: function() {

 var data = this.state.data;
 var header = this.state.header;

var columns = [
    {
        property: 'EFF_DT',
        header: 'EFF_DT',
	 },
    {
        property: 'ARP_CD',
        header: 'ARP_CD',
	},
];
 	sortingColumn: null,
	data = sortColumn.sort(data, this.state.sortingColumn);
        return (
		
            <div >
			<Table2 header={header} columns={columns} data={data} className="pure-table"/>
               </div>
        );
    },
	
});

**Comment by bebraw** [comment]
All I can see is that it chokes somewhere in that `sortColumn`. It has been at least six months since I wrote that code.

You could try adding a breakpoint there and digging in. That's what I would do in this case.

**Comment by ranjan653** [comment]
Hi, I have changed my approach of coding, Found below error. I think is it necessary to provide column type i.e string, number etc

![sortbyorder is noa function error](https://cloud.githubusercontent.com/assets/6347884/9954557/b0d86006-5e07-11e5-8ac1-7b1ea3854ad7.png)

**Comment by bebraw** [comment]
I think I can understand the problem now. Reactabular depends on lodash `sortByOrder`. Of course underscore doesn't implement that... I'll need to rewrite that part out...

**Comment by ranjan653** [comment]
Ok , waiting for your reply

**Comment by bebraw** [comment]
I patched it up. `sortByOrder` is included to Reactabular bundle now. Not ideal but fastest solution I could find... Tons of other work to do.

**Comment by ranjan653** [comment]
Still facing problem, will update soon

**Comment by ranjan653** [comment]
How can I pass Value of column within cross method


i.e ROWID VALUE IN onClick={remove.bind(this)}
{
	property: 'ROWID',
    header: 'ROWID',
	
                    cell: function(value, celldata, rowIndex) {
					console.log(rowIndex);
                        var idx = _.findIndex(this.state.data, {
						id: celldata[rowIndex].id,
    });
 

                        var remove = () => {
                            // this could go through flux etc.
						this.state.data.splice(rowIndex, 1);
						                            
                        };

                        return {
                            value: (
                                <span>
                                    
                                    <span className='remove' onClick={remove.bind(this)} style={{cursor: 'pointer'}}>
                                        &#10007;
                                    </span>
                                </span>
                            )
                        };
                    }.bind(this),
                },

**Comment by bebraw** [comment]
I'm not exactly sure what you are trying to achieve. Operation like delete should likely go through a backend. In this case you'll want to capture `onClick`, pass that `idx` to the backend and finally update data based on the result. Basic Flux.

**Comment by ranjan653** [comment]
My problem i can achieve on-click delete , but after search, Found 3 rows, now index of each row start with 0,1,2.
If I am deleting It delete from actual content data . If I can set value within on click then i can delete easily

**Comment by bebraw** [comment]
See `celldata[rowIndex]`. You can dig the id you might need for backend based delete from there.

Row indices are expected to work just like you describe. They are always 0, 1, 2 and so on. I hope that clears it up. These indices are separate from actual indices of your items.

It actually might be a good idea to hide the concept of `rowIndex` from the API to keep things simpler. Just passing the cell/row content would get far.

**Comment by ranjan653** [comment]
Yes sir,that I want to pass means front-end will show you cross img. but will pass  onclick that value.

Just like edit a particular thing we just pass id as value on click

**Comment by bebraw** [comment]
You can for instance do something like this:

```javascript
var remove = () => {
  var id = celldata[rowIndex].id;

  // do something with the id now,
  // hit backend etc.
};
```

You have access to the data within the outer scope due to the way JavaScript scoping works. Alternatively you can pass the value through bind. In this case you get `remove.bind(this, celldata[rowIndex].id)` and `var remove = (id) => {`. This is likely easier to test as you can push the function elsewhere.

**Comment by ranjan653** [comment]
Yes its working fine, am working toward next step. Thanks

**Comment by ranjan653** [comment]
Hi sir, I have implemented column sorting using static data (Fixed column and fixed rows)

could you please provide information regarding below lines

cell: [(followers) => followers - (followers % 100),
search: (followers) => followers - (followers % 100)

**Comment by bebraw** [comment]
`=>` is ES6 fat arrow syntax. That's a shortcut for `function() {...}.bind(this)`.

```javascript
cell: [(followers) => followers - (followers % 100),
search: (followers) => followers - (followers % 100)
```

is equivalent to

```
cell: [function(followers) {return followers - (followers % 100)},
search: function(followers) {return followers - (followers % 100)}
```

We don't need that `bind` here. Plain function definitions work just fine.

If you look at the math, it performs a floor operation over hundreds. Tweak as needed.

**Comment by ranjan653** [comment]
ok sir, Thank you
