### ISSUE TITLE
Cell value not updating properly in Reactabular

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#83]
Hello Sir,

First time If I change the value of cell its changing. After search or column sorting, there I face the problem.

First the data was like 
1
2
3

After sorting it looks like 
3
2
1

if I change the value of 3 then value of 1 changing not value of  3. 
For Find index I am using . Loadash.min.js library (_.findIndex)
My below code

var editable = cells.edit.bind(this, 'editedCell', (value, celldata, rowIndex, property) => {
           var idx = _.findIndex(this.state.data, { id: celldata[rowIndex].ROWID,});
     this.state.data[rowIndex][property] = value;

            this.setState({
                data: data123,
            });
        });

Need Help.?

**Comment by bebraw** [comment]
I would need a little online example to understand better. The official online demo appears to work as far as I can see. You would have to figure out where the difference is.

**Comment by ranjan653** [comment]
Sir, I found that, there is issue with row index

Can I pass one id to this editable like rowIndex, value

var editable = cells.edit.bind(this, 'editedCell', (value, celldata, rowIndex, property) => {
          
     this.state.data[rowIndex][property] = value;

            
        });

**Comment by bebraw** [comment]
You may need to do something along

```javascript
var that = this;

var editable = cells.edit.bind(this, 'editedCell', function(value, celldata, rowIndex, property) {
    var idx = findIndex(that.state.data, {
        id: celldata[rowIndex].ROWID,
    });

    that.state.data[idx][property] = value;

    that.setState({
        data: data,
    });
});
```

provided you cannot use fat arrow syntax yet. Alternatively you can bind `this` explicitly. Apart from this it's hard to say anything concrete without seeing something to debug.

**Comment by ranjan653** [comment]
For find index I am using _.findIndex available at loadash.min.js Its fine..

**Comment by ranjan653** [comment]
sir, 
var idx = _.findIndex(that.state.data, {
        id: celldata[rowIndex].ROWID,
    });

returning -1

**Comment by bebraw** [comment]
That just tells me it cannot find the data you expect. As I cannot debug
like this, can you try logging the values or setting a debugger; statement
there? it likely has something to do with the data definition but without
seeing any data it's impossible to tell.

**Comment by ranjan653** [comment]
My data 

var data=[{"EFF_DT":"2013-01-01","ARP_CD":"AAA","APT_LEVEL":"S","DEP_BANK_END":156,"OP_WED_IND":"0","OP_THU_IND":"1","OP_FRI_IND":"0","ROWID":"AAADWGAAMAABB7/AAH","TMST":"2013-01-16","BANK_NR":1,"OP_SUN_IND":"0","OP_MON_IND":"0","EMP_NR":"066404","OP_TUE_IND":"0","OP_SAT_IND":"0","DIS_DT":"2013-01-08","USR_GRP_CD":"12JUNTEST","ARR_BANK_END":1256,"ARR_BAN_BGN":1250,"DEP_BANK_BGN":59}]

**Comment by bebraw** [comment]
I suggest looking at it through a debugger. That will help you to understand what's going on. As suggested earlier, you can attach `debugger;` statement within that edit callback. Inspect the state. Hard to tell anything else.

**Comment by ranjan653** [comment]
ok sir
