### ISSUE TITLE
There is Issue with Reactabular search?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#85]
Hi,
I found there is issue with search in Reactabular.

I have clicked(Single Click) on Name: Angus Johnson and then searched with Name Daniel. But Instead of Daniel , its searching Daniel with Angus Johnson

Follow Screen shot.

![reactabular-search](https://cloud.githubusercontent.com/assets/6347884/10018592/b4553370-6155-11e5-9ffd-816c492f02a4.png)

**Comment by bebraw** [comment]
Good catch.

I wonder what would be the right way to resolve this. How would you expect this to work?

**Comment by ranjan653** [comment]
As usual like normal search.i.e Angus Johnson should not be in the list. Thanks a ton.

**Comment by ranjan653** [comment]
If we can allow the cell to edit on double click. I think It solve our problem.
