### ISSUE TITLE
Is It possible to implement data-picker in column of Reactabular ?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#86]
Hi 
Is It possible to implement data-picker in column of Reactabular ?

**Comment by bebraw** [comment]
See [Implementing Custom Cell Operations](https://github.com/bebraw/reactabular#implementing-custom-cell-operations). You can do whatever customizations you need through that interface.

**Comment by ranjan653** [comment]
Could you plz provide some example.?

**Comment by bebraw** [comment]
Can you link to the data picker you are familiar with? I'm not exactly sure what you need.

The simplest way for you to get started would be to copy the contents of [dropdown](https://github.com/bebraw/reactabular/blob/master/src/editors/dropdown.js) to your project. Rename that to datapicker or such and attach it to some cell. Once you get that working, you can try something more custom. Replace that `render()` method with something else. See the other editors for inspiration. It should be doable. :+1:

**Comment by ranjan653** [comment]
Hello Sir,

Please find the link
http://chrisharrington.github.io/demos/react/date-picker/
http://vitalets.github.io/bootstrap-datepicker/

**Comment by bebraw** [comment]
@ranjan653 If you can integrate one of those within the interface I provide that should work.

**Comment by ranjan653** [comment]
I am trying to implement, In case of react it is very difficult for me. But in Jquery it is easy. You are familiar with react that's why I am asking you. I am new to react just started development from this month.
If you will be part of this it like 
http://chrisharrington.github.io/demos/react/date-picker/
Then would be grateful.
Thanks

**Comment by ranjan653** [comment]
I can understand it should be like editors.dropdown==editors.datepicker...But

**Comment by bebraw** [comment]
I'm too busy with paying work at the moment.

If you can copy one of the existing editors and get it work first, that's a good starting point. After that you have to render the date picker you want through it.

The simplest way would be to go through [the standard solution](http://www.w3.org/TR/html-markup/input.date.html). Just set input type to date and let browser handle it. This won't work for old browsers though a polyfill may help.

**Comment by ranjan653** [comment]
Sir,
That should be mention in Reactabular.min.js.
I am only using Reactabular.min.js to achieve editor.input . So in which file i will write the code.

**Comment by bebraw** [comment]
@ranjan653 You can have a custom editor amongst your application code. All you need to do is to follow the interface as instructed at [the README](https://github.com/bebraw/reactabular#implementing-custom-cell-operations). A cell operation receives `value` and `onValue` through props. The former contains the value you should show at the editor. You should call the latter once done and pass the new value to it.

**Comment by ranjan653** [comment]
Hello sir,

Can I convert the date format in Reactabular

my json data is like "EFF_DT":"2013-01-01"  and I want to show the result in UI
as mm/dd/YYYY in Reactabular.

**Comment by bebraw** [comment]
@ranjan653 Sure, go through `cell`:

```javascript
cell: function(date) {
  // format date now. for example
  return (new Date(date)).toLocaleDateString();
} 
```

You can apply the formatting you want there. `toLocaleDateString` is a standard method and should work for most browsers. You can check exact support online.

**Comment by ranjan653** [comment]
Sir,
 {
        "property": "EFF_DT",
        "header": "Effective Date",		
        cell: [editable({editor: editors.input(),}),highlighter("EFF_DT")]
    }

How can I implement in this ?

**Comment by bebraw** [comment]
Perhaps

```javascript
cell: [editable({editor: editors.input(),}), dateFormatter, highlighter("EFF_DT")]

...

function dateFormatter(date) {
  // format date now. for example
  return (new Date(date)).toLocaleDateString();
} 
```

This is the point of the `cell` definition. Imagine it as a pipe. That will give you the correct order. See the demos for more examples.

**Comment by ranjan653** [comment]
SIr,
Here dateFormatter contains no parameter in cell but 
function dateFormatter(date) {
  // format date now. for example
  return (new Date(date)).toLocaleDateString();
} 

contains parameter.

Its throwing error.

**Comment by ranjan653** [comment]
hello sir,
Any solution...?

**Comment by bebraw** [comment]
> Its throwing error. ReferenceError: dateFormatter is not defined

Make sure you have `dateFormatter` in the correct scope. You can also write the function inline (replace `dateFormatter` with the function itself).

In case you run into problems with Date, look into [Moment.js](http://momentjs.com/).
