### ISSUE TITLE
Display long content in reactabular

### ISSUE THREAD

**Issue by thientran1707** [bebraw/reactabular#87]
Is there a good way to deal with very long content with reactabular? How to display them nicely?

**Comment by bebraw** [comment]
You could either solve this on CSS side somehow or pass it through something like <a href="https://bebraw.github.io/react-ellipsify/">react-ellipsify</a>.

Let me know if you find a good looking solution for this. I'm curious to know how other libraries deal with it.

**Comment by bebraw** [comment]
@thientran1707 Did you figure it out? You can always try plugging some nice component to a cell to deal with it. One interesting option would be to show the expanded data on hover through an `abbr` element.

**Comment by eviltoylet** [comment]
What does nicely mean to you? Scroll bars?

I'm with @bebraw on this one that a hover would be a nice thing to add. I would also add some sort of text area that would display a cell contents when it's clicked. (similar to Excel)

**Comment by bebraw** [comment]
It probably doesn't make sense to solve this at the core so I'm closing the issue.
