### ISSUE TITLE
How to create Dynamic tab Using React Js?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#90]
How to create Dynamic tab Using React Js?

**Comment by bebraw** [comment]
I'm going to need more information than that. You might need to resolve this outside of Reactabular, though.

**Comment by ranjan653** [comment]
ok sir,
Any reference ?

**Comment by bebraw** [comment]
@ranjan653 Can you link me to an example of what you need? I can dig out something for you based on that.

**Comment by ranjan653** [comment]
Hello sir,
http://www.jeasyui.com/tutorial/layout/tabs2_demo.html#
Here 3 buttons are there . But I have one select box on change the tabbed area will create and I will put Reactabular within tabbed area .

**Comment by bebraw** [comment]
Ok. I found these on a quick look:

* https://github.com/rackt/react-tabs
* https://github.com/pedronauck/react-simpletabs
* https://www.npmjs.com/package/react-tab-panel

Note that the fastest way to find components like these is to try [React.parts](http://react.parts/web) and [React Rocks](http://react.rocks/). Those are good starting points besides [npm](https://www.npmjs.com/).

**Comment by ranjan653** [comment]
OK Sir,
I have all these links, Trying......

**Comment by ranjan653** [comment]
Sir plan to visit India once ...:)

**Comment by bebraw** [comment]
We'll see. Probably a bit warm for my tastes. ;)

**Comment by ranjan653** [comment]
That's right boss.Here Most of the employees are knows you, as I have already share information about you.

**Comment by ranjan653** [comment]
Hi I just want hide and show reactabular ,its not working.

 <div show={this.state.showTable}>           
			    <div className='controls'>
                     <div className='search-container'>
                        Search <Search columns={columns} data={this.state.data} onChange={this.onSearch} />
                    </div>
                </div>
                <div id="constrainer">
			           <div className="scrolltable">
						            <Table2  header={header} columns={columns} data={data} row={(d, rowIndex) => {
						                        return {
						                            className: rowIndex % 2 ? 'odd-row' : 'even-row',                            
						                        };
						                    }} className="pure-table"/>
						
			               </div>
			               </div>
			               
               </div>



Coluld you plz suggest me..?
