### ISSUE TITLE
How to use Show and hide in reactabular ?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#91]
How to use Show and hide in reactabular ? I have tried but the search part and the header part is coming.
Please my reactabular code ...
![Uploading reactabular code.jpg…]()

**Comment by bebraw** [comment]
That's more general React problem. You'll need to wrap all of it within your visibility logic. Pseudocode:

```javascript
{showTable ? this.renderTable() : this.renderSomethingElse()}
```

`renderTable` would deal with search/header/table and so on while the other branch with the rest. The exact solution you want might be different but hopefully this puts you in the right direction.

**Comment by ranjan653** [comment]
Hi Sir,

Onclick tot working on React-bootstrap Tab

<Tab eventKey={2} title="Constraints" onClick={this.handleSelectTab}>
             </div>
            </Tab>

What is the solution for it?

Thanks
Ranjan

**Comment by bebraw** [comment]
Sorry, no idea as I don't use the library. Let's keep this issue tracker Reactabular specific only. :)
