### ISSUE TITLE
Multiple row select and remove using Reactabular?

### ISSUE THREAD

**Issue by ranjan653** [bebraw/reactabular#92]
Hello Sir,

Is it possible to select and remove multiple row using reactabular.

**Comment by bebraw** [comment]
This is something you'll have to implement outside of the core library. You should model some way to select a row (checkbox at custom column?) and then modify state based on that.

**Comment by ranjan653** [comment]
Just give idea how to implement check box.Need to change in library?

**Comment by bebraw** [comment]
No need to change library at all. There's [a cell hook](https://github.com/bebraw/reactabular#implementing-custom-cell-operations) for that. I would start from this:

```javascript
{
  property: 'selected',
  header: 'Selected',
  cell: function(value) {
    return <input type="checkbox" onValue={function() {
      ... alter your selection state ... }} selected={value} />
  }
}
```

So track your selection value somehow (now it assumes that your data model has `selected` field in it) and adjust it as the checkbox value changes. When you hit "remove" button somewhere in your UI, take the selection in count.

There are probably corner cases, like page change, which you may need to take into account somehow. Perhaps the easiest way to deal with this is simply to reset the selection when you are filtering the data somehow for example.

I hope this helps.

**Comment by ranjan653** [comment]
Ok sir I am trying..
