### ISSUE TITLE
change dropdown.js 

### ISSUE THREAD

**Issue by limweb** [bebraw/reactabular#93]
'use strict';

var React = require('react/addons');

module.exports = (options,datafield,labelfield) => {

    return React.createClass({
        displayName: 'Dropdown',
        propTypes: {
            value: React.PropTypes.string,
            onValue: React.PropTypes.func,
        },

        render() {
            datafield = datafield || 'value';
            labelfield = labelfield || 'name';
            var edit = (e) => this.props.onValue(e.target.value);

            return (
                <select onBlur={edit} onChange={edit} value={this.props.value}>
                    {options.map((option, i) =>
                        <option
                            key={i}
                            value={option[datafield]}
                        >{option[labelfield]}</option>
                    )}
                </select>
            );
        }
    });
};

add to parametor  datafield  default value  and  labelfield  default is name ;

in   editor:editors.dropdown(datasources.orders,'id','firstname'),

**Comment by bebraw** [comment]
Sure. Do you want to do a PR or should I patch it?

**Comment by limweb** [comment]
plase patch it. thanks.

**Comment by bebraw** [comment]
`0.7.5` contains the feature. I have a feeling it might be a good idea to separate the core and the editors at some point so those can be maintained separately.

Here's the API: `editors.dropdown(countries, {name: <name>, value: <value>})`.
