### ISSUE TITLE
How to change the width of just one column? 

### ISSUE THREAD

**Issue by 90abyss** [bebraw/reactabular#98]
I couldn't find the CSS file responsible for changing the width of just one column. I am trying to display a Tweet in one of the columns so I need for it to be bigger than the rest.

**Comment by bebraw** [comment]
You could try to attach

```javascript
classes: {'twitter-column': true}
```

to your column definition and then force the width through CSS in a way that makes the most sense to you. At simplest you just set

```javascript
.twitter-column {
  width: 5em;
}
```

**Comment by 90abyss** [comment]
I'm playing around with your full_table.jsx and this is what I've done so far to change the column width:

contents of full_table.jsx file:

'use strict'
import './override.css';

...

{
     property: 'TweetText',
     header: 'Tweet Text',
     classes: {'TweetText': true},
}


contents of file override.css:

.TweetText{
  width: 10em;
}


No changes are rendered. Any ideas?

**Comment by bebraw** [comment]
@90abyss Can you check that the class gets set at your `th` correctly through Chrome Inspector or a similar tool? It will help if you can set up a little online demo for me to check out. A GitHub repository would work.

**Comment by 90abyss** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/6945738/10561250/c8106184-74ef-11e5-8c26-f7caa6603a68.png)

as you can see th is getting set correctly.

**Comment by 90abyss** [comment]
Also - if I do this:

.TweetText{
  background: #fafafa;
}

then changed are getting reflected correctly. 

But if I do this:

.TweetText{
  width: 100em;
}

Then they are not.

**Comment by bebraw** [comment]
@90abyss Ok. It has something to do with `em`. If I set `100px` or similar, it works for me. Too late to debug with a clear head.

**Comment by 90abyss** [comment]
px is not working for me either :(

![selection_002](https://cloud.githubusercontent.com/assets/6945738/10561340/7557bdfe-74f2-11e5-9440-ca523d5e1e61.png)

Please let me know when you find a fix to this. Any work around will help immensely

**Comment by bebraw** [comment]
@90abyss Works for me. See https://bebraw.github.io/reactabular-demo/ . It's very difficult for me to help unless you can set up a failing example to study.

**Comment by 90abyss** [comment]
hey bebraw! can you please take a look at this:
https://github.com/90abyss/reactabular
this is the example thats not working. I'm basically making edits in your full_table.jsx file itself.

I need to do two things:
1) increase column width of the column TweetText. (currently I have a override.css imported)
2) shift the table to the left 

I am just not able to access any css properties to do that. can you please help me? Thanks.

**Comment by bebraw** [comment]
Maybe it's just neater to inject a div there and force the width through that:

```javascript
{
    property: 'TweetText',
    header: 'Tweettext',
    //classes: {'TweetText': true},
    cell: [
        editable({
            editor: editors.input(),
        }),
        (v) => <div style={{width: 100}}>
            {highlighter('TweetText')(v)}
        </div>
    ]
},
```

Alternatively you could set `className` there and style through CSS. Or you could set `className` of the `td` through [the cell interface](https://github.com/bebraw/reactabular#implementing-custom-cell-operations).

[Other ideas](https://stackoverflow.com/questions/4457506/set-the-table-column-width-constant-regardless-of-the-amount-of-text-in-its-cell).

**Comment by 90abyss** [comment]
bebraw -  Thank you so much! It totally worked. You have no idea how much you have helped me by creating this reactabular. Keep up the good work!!

Another qs - how do I shift the entire table to the extreme left? Its positioned at the center at the moment and therefore there is lots of white space to the left.

Thanks again!

**Comment by bebraw** [comment]
@90abyss Note that I set `max-width: 768px;` for `article` at *main.css*. If you remove that, it will get rid of the centering.

I noticed a little search related glitch at your demo. I published a new version with fixed behavior.

**Comment by 90abyss** [comment]
perfect! also another thing - is there a way to lock the first three columns and keep them fixed while you scroll to the right. Also how can I highlight a row like we do in excel?

Thanks so much bebraw for all your help. You have no idea how much reactabular has helped me.

**Comment by bebraw** [comment]
> perfect! also another thing - is there a way to lock the first three columns and keep them fixed while you scroll to the right. Also how can I highlight a row like we do in excel?

I have a feeling you might be able to pull of the first one with CSS somehow. You would need to listen to window scroll through React and apply some CSS trickery there. It likely doesn't make sense to solve this in Reactabular itself.

You should be able to solve the latter through [the row prop interface](https://github.com/bebraw/reactabular#attaching-props-per-row). Check against `rowIndex` and set `className` based on that to highlight the row you want.

**Comment by 90abyss** [comment]
Great! I will look into it. 

Any ideas on how should I integrate user authentication? Will I have to make changes in index.jsx or webpack.config.js file and ask for user authentication first or something of the like? Please let me know how should I proceed with this.

Thanks so much.

**Comment by 90abyss** [comment]
Also - one last thing - I noticed that the app always runs on localhost:8080. How can I make it publicly accessible? How do I change the port to 80?

**Comment by bebraw** [comment]
> Any ideas on how should I integrate http authentication? Will I have to make changes in index.jsx or webpack.config.js file and ask for user authentication first or something of the like? Please let me know how should I proceed with this.

Note that `npm start` is not meant to be used for production. It's better if you execute `npm run gh-pages` and host that output.

Authentication is a bigger problem and there are multiple ways to approach that. It's hard to give a single answer as that depends on your environment. It's better to ask this sort of questions at [Reactiflux](http://www.reactiflux.com/) given the go beyond Reactabular.
