### ISSUE TITLE
unable to install on windows

### ISSUE THREAD

**Issue by 90abyss** [bebraw/reactabular#99]
my command prompt output after doing npm install:

reactabular@0.8.3 postinstall C:\Users\x\Downloads\wth\reactabular-master
node lib/post_install.js

C:\Users\x\Downloads\wth\reactabular-master\lib\post_install.js:7
    execSync(command, {
    ^\
TypeError: undefined is not a function
    at exec (C:\Users\x\Downloads\wth\reactabular-master\lib\post_install.js:7:5)
    at C:\Users\x\Downloads\wth\reactabular-master\lib\post_install.js:14:9
    at Object.oncomplete (fs.js:107:15)

npm ERR! reactabular@0.8.3 postinstall: `node lib/post_install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the reactabular@0.8.3 postinstall script.
npm ERR! This is most likely a problem with the reactabular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls reactabular
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\x\Downloads\wth\reactabular-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\x\Downloads\wth\reactabular-master\npm-debug.log
npm ERR! not ok code 0

**Comment by 90abyss** [comment]
my log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ 'C:\\Users\\rukshi\\Downloads\\wth\\reactabular-master',
6 verbose install   [ 'classnames',
6 verbose install     'lodash.sortbyorder',
6 verbose install     'annogenerate',
6 verbose install     'annomath',
6 verbose install     'babel',
6 verbose install     'babel-core',
6 verbose install     'babel-eslint',
6 verbose install     'babel-loader',
6 verbose install     'babel-plugin-react-transform',
6 verbose install     'chai',
6 verbose install     'clean-webpack-plugin',
6 verbose install     'css-loader',
6 verbose install     'eslint',
6 verbose install     'eslint-plugin-react',
6 verbose install     'file-loader',
6 verbose install     'gh-pages',
6 verbose install     'highlight.js',
6 verbose install     'html-loader',
6 verbose install     'html-webpack-plugin',
6 verbose install     'isparta-instrumenter-loader',
6 verbose install     'karma',
6 verbose install     'karma-chai',
6 verbose install     'karma-coverage',
6 verbose install     'karma-mocha',
6 verbose install     'karma-phantomjs-launcher',
6 verbose install     'karma-sourcemap-loader',
6 verbose install     'karma-spec-reporter',
6 verbose install     'karma-webpack',
6 verbose install     'lodash',
6 verbose install     'marked',
6 verbose install     'mocha',
6 verbose install     'phantomjs',
6 verbose install     'phantomjs-polyfill',
6 verbose install     'plexus-form',
6 verbose install     'plexus-validate',
6 verbose install     'purecss',
6 verbose install     'react',
6 verbose install     'react-ghfork',
6 verbose install     'react-pagify',
6 verbose install     'react-skylight',
6 verbose install     'react-transform-hmr',
6 verbose install     'schema2object',
6 verbose install     'style-loader',
6 verbose install     'title-case',
6 verbose install     'url-loader',
6 verbose install     'webpack',
6 verbose install     'webpack-dev-server',
6 verbose install     'webpack-merge' ] ]
7 info preinstall reactabular@0.8.3
8 verbose readDependencies using package.json deps
9 verbose already installed skipping highlight.js@^8.8.0 C:\Users\rukshi\Downloads\wth\reactabular-master
10 verbose already installed skipping classnames@^2.1.3 C:\Users\rukshi\Downloads\wth\reactabular-master
11 verbose already installed skipping lodash.sortbyorder@^3.4.4 C:\Users\rukshi\Downloads\wth\reactabular-master
12 verbose already installed skipping annogenerate@^0.8.1 C:\Users\rukshi\Downloads\wth\reactabular-master
13 verbose already installed skipping annomath@^0.4.1 C:\Users\rukshi\Downloads\wth\reactabular-master
14 verbose already installed skipping babel@^5.8.23 C:\Users\rukshi\Downloads\wth\reactabular-master
15 verbose already installed skipping babel-core@^5.8.25 C:\Users\rukshi\Downloads\wth\reactabular-master
16 verbose already installed skipping babel-eslint@^4.1.3 C:\Users\rukshi\Downloads\wth\reactabular-master
17 verbose already installed skipping babel-loader@^5.3.2 C:\Users\rukshi\Downloads\wth\reactabular-master
18 verbose already installed skipping babel-plugin-react-transform@^1.1.1 C:\Users\rukshi\Downloads\wth\reactabular-master
19 verbose already installed skipping chai@^3.3.0 C:\Users\rukshi\Downloads\wth\reactabular-master
20 verbose already installed skipping clean-webpack-plugin@^0.1.3 C:\Users\rukshi\Downloads\wth\reactabular-master
21 verbose already installed skipping css-loader@^0.18.0 C:\Users\rukshi\Downloads\wth\reactabular-master
22 verbose already installed skipping eslint@^1.5.0 C:\Users\rukshi\Downloads\wth\reactabular-master
23 verbose already installed skipping eslint-plugin-react@^3.4.2 C:\Users\rukshi\Downloads\wth\reactabular-master
24 verbose already installed skipping file-loader@^0.8.4 C:\Users\rukshi\Downloads\wth\reactabular-master
25 verbose already installed skipping gh-pages@^0.4.0 C:\Users\rukshi\Downloads\wth\reactabular-master
26 verbose already installed skipping html-loader@^0.3.0 C:\Users\rukshi\Downloads\wth\reactabular-master
27 verbose already installed skipping html-webpack-plugin@^1.6.1 C:\Users\rukshi\Downloads\wth\reactabular-master
28 verbose already installed skipping isparta-instrumenter-loader@^0.2.1 C:\Users\rukshi\Downloads\wth\reactabular-master
29 verbose already installed skipping karma@^0.13.10 C:\Users\rukshi\Downloads\wth\reactabular-master
30 verbose already installed skipping karma-chai@^0.1.0 C:\Users\rukshi\Downloads\wth\reactabular-master
31 verbose already installed skipping karma-coverage@^0.5.2 C:\Users\rukshi\Downloads\wth\reactabular-master
32 verbose already installed skipping karma-mocha@^0.2.0 C:\Users\rukshi\Downloads\wth\reactabular-master
33 verbose already installed skipping karma-phantomjs-launcher@^0.2.1 C:\Users\rukshi\Downloads\wth\reactabular-master
34 verbose already installed skipping karma-sourcemap-loader@^0.3.5 C:\Users\rukshi\Downloads\wth\reactabular-master
35 verbose already installed skipping karma-spec-reporter@0.0.20 C:\Users\rukshi\Downloads\wth\reactabular-master
36 verbose already installed skipping karma-webpack@^1.7.0 C:\Users\rukshi\Downloads\wth\reactabular-master
37 verbose already installed skipping lodash@^3.10.1 C:\Users\rukshi\Downloads\wth\reactabular-master
38 verbose already installed skipping marked@^0.3.5 C:\Users\rukshi\Downloads\wth\reactabular-master
39 verbose already installed skipping mocha@^2.3.3 C:\Users\rukshi\Downloads\wth\reactabular-master
40 verbose already installed skipping phantomjs@^1.9.18 C:\Users\rukshi\Downloads\wth\reactabular-master
41 verbose already installed skipping phantomjs-polyfill@0.0.1 C:\Users\rukshi\Downloads\wth\reactabular-master
42 verbose already installed skipping plexus-form@^0.1.3 C:\Users\rukshi\Downloads\wth\reactabular-master
43 verbose already installed skipping plexus-validate@^0.0.4 C:\Users\rukshi\Downloads\wth\reactabular-master
44 verbose already installed skipping purecss@^0.6.0 C:\Users\rukshi\Downloads\wth\reactabular-master
45 verbose already installed skipping react@^0.13.3 C:\Users\rukshi\Downloads\wth\reactabular-master
46 verbose already installed skipping react-ghfork@^0.3.2 C:\Users\rukshi\Downloads\wth\reactabular-master
47 verbose already installed skipping react-pagify@^0.8.1 C:\Users\rukshi\Downloads\wth\reactabular-master
48 verbose already installed skipping react-skylight@^0.2.0 C:\Users\rukshi\Downloads\wth\reactabular-master
49 verbose already installed skipping react-transform-hmr@^1.0.1 C:\Users\rukshi\Downloads\wth\reactabular-master
50 verbose already installed skipping schema2object@^0.4.0 C:\Users\rukshi\Downloads\wth\reactabular-master
51 verbose already installed skipping style-loader@^0.12.4 C:\Users\rukshi\Downloads\wth\reactabular-master
52 verbose already installed skipping title-case@^1.1.1 C:\Users\rukshi\Downloads\wth\reactabular-master
53 verbose already installed skipping url-loader@^0.5.6 C:\Users\rukshi\Downloads\wth\reactabular-master
54 verbose already installed skipping webpack@^1.12.2 C:\Users\rukshi\Downloads\wth\reactabular-master
55 verbose already installed skipping webpack-dev-server@^1.11.0 C:\Users\rukshi\Downloads\wth\reactabular-master
56 verbose already installed skipping webpack-merge@^0.2.0 C:\Users\rukshi\Downloads\wth\reactabular-master
57 silly resolved []
58 info build C:\Users\rukshi\Downloads\wth\reactabular-master
59 verbose linkStuff [ false, false, false, 'C:\\Users\\rukshi\\Downloads\\wth' ]
60 info linkStuff reactabular@0.8.3
61 verbose linkBins reactabular@0.8.3
62 verbose linkMans reactabular@0.8.3
63 verbose rebuildBundles reactabular@0.8.3
64 verbose rebuildBundles [ '.bin',
64 verbose rebuildBundles   'annogenerate',
64 verbose rebuildBundles   'annomath',
64 verbose rebuildBundles   'babel',
64 verbose rebuildBundles   'babel-core',
64 verbose rebuildBundles   'babel-eslint',
64 verbose rebuildBundles   'babel-loader',
64 verbose rebuildBundles   'babel-plugin-react-transform',
64 verbose rebuildBundles   'chai',
64 verbose rebuildBundles   'classnames',
64 verbose rebuildBundles   'clean-webpack-plugin',
64 verbose rebuildBundles   'css-loader',
64 verbose rebuildBundles   'eslint',
64 verbose rebuildBundles   'eslint-plugin-react',
64 verbose rebuildBundles   'file-loader',
64 verbose rebuildBundles   'gh-pages',
64 verbose rebuildBundles   'highlight.js',
64 verbose rebuildBundles   'html-loader',
64 verbose rebuildBundles   'html-webpack-plugin',
64 verbose rebuildBundles   'isparta-instrumenter-loader',
64 verbose rebuildBundles   'karma',
64 verbose rebuildBundles   'karma-chai',
64 verbose rebuildBundles   'karma-coverage',
64 verbose rebuildBundles   'karma-mocha',
64 verbose rebuildBundles   'karma-phantomjs-launcher',
64 verbose rebuildBundles   'karma-sourcemap-loader',
64 verbose rebuildBundles   'karma-spec-reporter',
64 verbose rebuildBundles   'karma-webpack',
64 verbose rebuildBundles   'lodash',
64 verbose rebuildBundles   'lodash.sortbyorder',
64 verbose rebuildBundles   'marked',
64 verbose rebuildBundles   'mocha',
64 verbose rebuildBundles   'phantomjs',
64 verbose rebuildBundles   'phantomjs-polyfill',
64 verbose rebuildBundles   'plexus-form',
64 verbose rebuildBundles   'plexus-validate',
64 verbose rebuildBundles   'purecss',
64 verbose rebuildBundles   'react',
64 verbose rebuildBundles   'react-ghfork',
64 verbose rebuildBundles   'react-pagify',
64 verbose rebuildBundles   'react-skylight',
64 verbose rebuildBundles   'react-transform-hmr',
64 verbose rebuildBundles   'schema2object',
64 verbose rebuildBundles   'style-loader',
64 verbose rebuildBundles   'title-case',
64 verbose rebuildBundles   'url-loader',
64 verbose rebuildBundles   'webpack',
64 verbose rebuildBundles   'webpack-dev-server',
64 verbose rebuildBundles   'webpack-merge' ]
65 info install reactabular@0.8.3
66 info postinstall reactabular@0.8.3
67 verbose unsafe-perm in lifecycle true
68 info reactabular@0.8.3 Failed to exec postinstall script
69 error reactabular@0.8.3 postinstall: `node lib/post_install.js`
69 error Exit status 8
70 error Failed at the reactabular@0.8.3 postinstall script.
70 error This is most likely a problem with the reactabular package,
70 error not with npm itself.
70 error Tell the author that this fails on your system:
70 error     node lib/post_install.js
70 error You can get their info via:
70 error     npm owner ls reactabular
70 error There is likely additional logging output above.
71 error System Windows_NT 6.2.9200
72 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
73 error cwd C:\Users\rukshi\Downloads\wth\reactabular-master
74 error node -v v0.10.29
75 error npm -v 1.4.14
76 error code ELIFECYCLE
77 verbose exit [ 1, true ]

**Comment by bebraw** [comment]
Node 0.10 isn't supported at the moment given it's so old.

This can be fixed by tweaking the [postinstall script](https://github.com/bebraw/reactabular/blob/master/lib/post_install.js). We would need to detect Node 0.10 there somehow and then do the equivalent of `require('child_process').execSync` there. If you can dig how to do this, I can patch it. Alternatively a PR is welcome.

**Comment by 90abyss** [comment]
After updating the node to 4.2.1 I'm getting this error:

C:\Users\x\Downloads\wth\reactabular-master>npm start

> reactabular@0.8.3 start C:\Users\x\Downloads\wth\reactabular-master
> webpack-dev-server

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! reactabular@0.8.3 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactabular@0.8.3 start script 'webpack-dev-server'.
npm ERR! This is most likely a problem with the reactabular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls reactabular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\x\Downloads\wth\reactabular-master\npm-debug.log

**Comment by 90abyss** [comment]
log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart reactabular@0.8.3
6 info start reactabular@0.8.3
7 verbose unsafe-perm in lifecycle true
8 info reactabular@0.8.3 Failed to exec start script
9 verbose stack Error: reactabular@0.8.3 start: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid reactabular@0.8.3
11 verbose cwd C:\Users\x\Downloads\wth\reactabular-master
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error reactabular@0.8.3 start: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the reactabular@0.8.3 start script 'webpack-dev-server'.
18 error This is most likely a problem with the reactabular package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls reactabular
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by bebraw** [comment]
> C:\Users\x\Downloads\wth\reactabular-master>npm start

Why are you trying to run the package in development mode?

> Error: listen EACCES 127.0.0.1:8080

That might be environment/permission related. For some reason it's not letting the dev server to run through 8080 but it's hard to tell anything else as I don't have access to Windows.

**Comment by 90abyss** [comment]
How do I run the package in the non development mode?

**Comment by 90abyss** [comment]
Also if 8080 is blocked, is there another way to npm install using a different port?

**Comment by bebraw** [comment]
@90abyss There's no need to run it. The npm version has been designed to be consumed through Node/browserify/Webpack and such. In Webpack environment you would work like this:

1. `npm i reactabular --save` - Save as project dependency.
2. `import {Table} from 'reactabular'`- Import where you need it. This assumes ES6 (Babel or similar system). You can also do `var Table = require('reactabular').Table;`

There's also a source distribution below `dist/` if you cannot consume the package through npm for a reason or another.

**Comment by 90abyss** [comment]
Hey! As you must have noticed I am a newbie in programming and don't have much idea how to use these frameworks. So can you please help me with this - this is what I have done so far:

1) npm i reactabular --save to create project dependency. This created nodes_modules folder inside.

2) my html file:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id="content"></div>
    <script src="scripts/test.js"></script>
  </body>
</html>


3) my JS file:

var Table = require('reactabular').Table;

var data = [
{
name: 'React.js',
type: 'library',
description: 'Awesome library for handling view.',
followers: 23252,
worksWithReactabular: true,
id: 123
},
];

var columns = [
{
property: 'name',
header: 'Name',
classes: {'name-column': true}, // custom CSS classes
},
{
property: 'type',
header: 'Type',
},
{
property: 'description',
header: 'Description',
},
{
property: 'followers',
header: 'Followers',
// accuracy per hundred is enough for demoing
cell: (followers) => followers - (followers % 100),
},
{
property: 'worksWithReactabular',
header: '1st Class Reactabular',
// render utf ok if works
cell: (works) => works && <span>&#10003;</span>,
},
];

ReactDOM.render(
<Table columns={columns} data={data} />,
document.getElementById('content')
);



I'm not getting any output after clicking on the html page. Can you please help me?

**Comment by bebraw** [comment]
@90abyss Can you check out [my book](http://survivejs.com/) about the topic? The free portions should help you to get started with Webpack and React. If you want to jump straight in, you can try my [boilerplate](https://survivejs.github.io/react-component-boilerplate/). It has everything set up.

**Comment by 90abyss** [comment]
Thanks a lot kind sir :)

**Comment by bebraw** [comment]
Ok, it's probably safe to close this now. :+1:
